/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InternalServerErrorResponse,
  KeystoreApplicationConfig
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get application config
 */
export type getApplicationConfigResponse200 = {
  data: KeystoreApplicationConfig
  status: 200
}

export type getApplicationConfigResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type getApplicationConfigResponseSuccess = (getApplicationConfigResponse200) & {
  headers: Headers;
};
export type getApplicationConfigResponseError = (getApplicationConfigResponse500) & {
  headers: Headers;
};

export type getApplicationConfigResponse = (getApplicationConfigResponseSuccess | getApplicationConfigResponseError)

export const getGetApplicationConfigUrl = () => {


  

  return `/v1/keystore/config`
}

export const getApplicationConfig = async ( options?: RequestInit): Promise<getApplicationConfigResponse> => {
  
  return customInstance<getApplicationConfigResponse>(getGetApplicationConfigUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApplicationConfigInfiniteQueryKey = () => {
    return [
    'infinite', `/v1/keystore/config`
    ] as const;
    }

export const getGetApplicationConfigQueryKey = () => {
    return [
    `/v1/keystore/config`
    ] as const;
    }

    
export const getGetApplicationConfigInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApplicationConfig>>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationConfigInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplicationConfig>>> = ({ signal }) => getApplicationConfig({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApplicationConfigInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApplicationConfig>>>
export type GetApplicationConfigInfiniteQueryError = ErrorType<InternalServerErrorResponse>


export function useGetApplicationConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApplicationConfig>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationConfig>>,
          TError,
          Awaited<ReturnType<typeof getApplicationConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApplicationConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApplicationConfig>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationConfig>>,
          TError,
          Awaited<ReturnType<typeof getApplicationConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApplicationConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApplicationConfig>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get application config
 */

export function useGetApplicationConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApplicationConfig>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApplicationConfigInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetApplicationConfigQueryOptions = <TData = Awaited<ReturnType<typeof getApplicationConfig>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationConfigQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplicationConfig>>> = ({ signal }) => getApplicationConfig({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApplicationConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getApplicationConfig>>>
export type GetApplicationConfigQueryError = ErrorType<InternalServerErrorResponse>


export function useGetApplicationConfig<TData = Awaited<ReturnType<typeof getApplicationConfig>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationConfig>>,
          TError,
          Awaited<ReturnType<typeof getApplicationConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApplicationConfig<TData = Awaited<ReturnType<typeof getApplicationConfig>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationConfig>>,
          TError,
          Awaited<ReturnType<typeof getApplicationConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApplicationConfig<TData = Awaited<ReturnType<typeof getApplicationConfig>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get application config
 */

export function useGetApplicationConfig<TData = Awaited<ReturnType<typeof getApplicationConfig>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApplicationConfigQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




