/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FeConfig,
  SessionUser,
  UnauthorizedResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Runtime configuration of the admin GUI
 */
export type getFeConfigResponse200 = {
  data: FeConfig
  status: 200
}
    
export type getFeConfigResponseSuccess = (getFeConfigResponse200) & {
  headers: Headers;
};
;

export type getFeConfigResponse = (getFeConfigResponseSuccess)

export const getGetFeConfigUrl = () => {


  

  return `/fe-config`
}

export const getFeConfig = async ( options?: RequestInit): Promise<getFeConfigResponse> => {
  
  return customInstance<getFeConfigResponse>(getGetFeConfigUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetFeConfigInfiniteQueryKey = () => {
    return [
    'infinite', `/fe-config`
    ] as const;
    }

export const getGetFeConfigQueryKey = () => {
    return [
    `/fe-config`
    ] as const;
    }

    
export const getGetFeConfigInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getFeConfig>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFeConfigInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeConfig>>> = ({ signal }) => getFeConfig({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetFeConfigInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getFeConfig>>>
export type GetFeConfigInfiniteQueryError = ErrorType<unknown>


export function useGetFeConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getFeConfig>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeConfig>>,
          TError,
          Awaited<ReturnType<typeof getFeConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetFeConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getFeConfig>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeConfig>>,
          TError,
          Awaited<ReturnType<typeof getFeConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetFeConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getFeConfig>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Runtime configuration of the admin GUI
 */

export function useGetFeConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getFeConfig>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetFeConfigInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetFeConfigQueryOptions = <TData = Awaited<ReturnType<typeof getFeConfig>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFeConfigQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeConfig>>> = ({ signal }) => getFeConfig({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetFeConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getFeConfig>>>
export type GetFeConfigQueryError = ErrorType<unknown>


export function useGetFeConfig<TData = Awaited<ReturnType<typeof getFeConfig>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeConfig>>,
          TError,
          Awaited<ReturnType<typeof getFeConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetFeConfig<TData = Awaited<ReturnType<typeof getFeConfig>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeConfig>>,
          TError,
          Awaited<ReturnType<typeof getFeConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetFeConfig<TData = Awaited<ReturnType<typeof getFeConfig>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Runtime configuration of the admin GUI
 */

export function useGetFeConfig<TData = Awaited<ReturnType<typeof getFeConfig>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeConfig>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetFeConfigQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * The user the gateway's identity provider gives for this session (with Keycloak, the one
oauth2-proxy signed in; in `static` mode, the configured user). 401 when there is no
session: the console then sends the browser to the proxy's sign-in (`/oauth2/start`).

 * @summary Who the browser's session is
 */
export type getSessionUserResponse200 = {
  data: SessionUser
  status: 200
}

export type getSessionUserResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type getSessionUserResponseSuccess = (getSessionUserResponse200) & {
  headers: Headers;
};
export type getSessionUserResponseError = (getSessionUserResponse401) & {
  headers: Headers;
};

export type getSessionUserResponse = (getSessionUserResponseSuccess | getSessionUserResponseError)

export const getGetSessionUserUrl = () => {


  

  return `/me`
}

export const getSessionUser = async ( options?: RequestInit): Promise<getSessionUserResponse> => {
  
  return customInstance<getSessionUserResponse>(getGetSessionUserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSessionUserInfiniteQueryKey = () => {
    return [
    'infinite', `/me`
    ] as const;
    }

export const getGetSessionUserQueryKey = () => {
    return [
    `/me`
    ] as const;
    }

    
export const getGetSessionUserInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getSessionUser>>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionUserInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSessionUser>>> = ({ signal }) => getSessionUser({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetSessionUserInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getSessionUser>>>
export type GetSessionUserInfiniteQueryError = ErrorType<UnauthorizedResponse>


export function useGetSessionUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSessionUser>>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionUser>>,
          TError,
          Awaited<ReturnType<typeof getSessionUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSessionUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSessionUser>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionUser>>,
          TError,
          Awaited<ReturnType<typeof getSessionUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSessionUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSessionUser>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Who the browser's session is
 */

export function useGetSessionUserInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSessionUser>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetSessionUserInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetSessionUserQueryOptions = <TData = Awaited<ReturnType<typeof getSessionUser>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSessionUser>>> = ({ signal }) => getSessionUser({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetSessionUserQueryResult = NonNullable<Awaited<ReturnType<typeof getSessionUser>>>
export type GetSessionUserQueryError = ErrorType<UnauthorizedResponse>


export function useGetSessionUser<TData = Awaited<ReturnType<typeof getSessionUser>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionUser>>,
          TError,
          Awaited<ReturnType<typeof getSessionUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSessionUser<TData = Awaited<ReturnType<typeof getSessionUser>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSessionUser>>,
          TError,
          Awaited<ReturnType<typeof getSessionUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSessionUser<TData = Awaited<ReturnType<typeof getSessionUser>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Who the browser's session is
 */

export function useGetSessionUser<TData = Awaited<ReturnType<typeof getSessionUser>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetSessionUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




