# https://taskfile.dev
version: '3'

includes:
  docker:
    taskfile: ./scripts/Taskfile.docker.yml
    dir: .
  env:
    taskfile: ./scripts/Taskfile.dev.yml
    dir: .
  deployment:
    taskfile: ./deployment/Taskfile.deployment.yml
    dir: .

tasks:
  banner:
    desc: Add license header to all source files
    cmds:
      - bash ./scripts/add_license.sh .
