/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  ConflictResponse,
  ForbiddenResponse,
  InternalServerErrorResponse,
  KeystoreEditSecretCommand,
  KeystoreNewSecretCommand,
  KeystoreSecretView,
  KeystoreVersionResponse,
  ListSecretsParams,
  NotFoundResponse,
  UnauthorizedResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List secrets
 */
export type listSecretsResponse200 = {
  data: KeystoreSecretView[]
  status: 200
}

export type listSecretsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listSecretsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type listSecretsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type listSecretsResponseSuccess = (listSecretsResponse200) & {
  headers: Headers;
};
export type listSecretsResponseError = (listSecretsResponse401 | listSecretsResponse403 | listSecretsResponse500) & {
  headers: Headers;
};

export type listSecretsResponse = (listSecretsResponseSuccess | listSecretsResponseError)

export const getListSecretsUrl = (params?: ListSecretsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/keystore/secrets?${stringifiedParams}` : `/v1/keystore/secrets`
}

export const listSecrets = async (params?: ListSecretsParams, options?: RequestInit): Promise<listSecretsResponse> => {
  
  return customInstance<listSecretsResponse>(getListSecretsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListSecretsInfiniteQueryKey = (params?: ListSecretsParams,) => {
    return [
    'infinite', `/v1/keystore/secrets`, ...(params ? [params] : [])
    ] as const;
    }

export const getListSecretsQueryKey = (params?: ListSecretsParams,) => {
    return [
    `/v1/keystore/secrets`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListSecretsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listSecrets>>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>>(params?: ListSecretsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSecretsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSecrets>>> = ({ signal }) => listSecrets(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListSecretsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listSecrets>>>
export type ListSecretsInfiniteQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>


export function useListSecretsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listSecrets>>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>>(
 params: undefined |  ListSecretsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSecrets>>,
          TError,
          Awaited<ReturnType<typeof listSecrets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListSecretsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listSecrets>>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>>(
 params?: ListSecretsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSecrets>>,
          TError,
          Awaited<ReturnType<typeof listSecrets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListSecretsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listSecrets>>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>>(
 params?: ListSecretsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List secrets
 */

export function useListSecretsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listSecrets>>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>>(
 params?: ListSecretsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListSecretsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListSecretsQueryOptions = <TData = Awaited<ReturnType<typeof listSecrets>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>>(params?: ListSecretsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSecretsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSecrets>>> = ({ signal }) => listSecrets(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListSecretsQueryResult = NonNullable<Awaited<ReturnType<typeof listSecrets>>>
export type ListSecretsQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>


export function useListSecrets<TData = Awaited<ReturnType<typeof listSecrets>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>>(
 params: undefined |  ListSecretsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSecrets>>,
          TError,
          Awaited<ReturnType<typeof listSecrets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListSecrets<TData = Awaited<ReturnType<typeof listSecrets>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>>(
 params?: ListSecretsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSecrets>>,
          TError,
          Awaited<ReturnType<typeof listSecrets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListSecrets<TData = Awaited<ReturnType<typeof listSecrets>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>>(
 params?: ListSecretsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List secrets
 */

export function useListSecrets<TData = Awaited<ReturnType<typeof listSecrets>>, TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>>(
 params?: ListSecretsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListSecretsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a secret
 */
export type createSecretResponse201 = {
  data: KeystoreSecretView
  status: 201
}

export type createSecretResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createSecretResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createSecretResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createSecretResponse409 = {
  data: ConflictResponse
  status: 409
}

export type createSecretResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type createSecretResponseSuccess = (createSecretResponse201) & {
  headers: Headers;
};
export type createSecretResponseError = (createSecretResponse400 | createSecretResponse401 | createSecretResponse403 | createSecretResponse409 | createSecretResponse500) & {
  headers: Headers;
};

export type createSecretResponse = (createSecretResponseSuccess | createSecretResponseError)

export const getCreateSecretUrl = () => {


  

  return `/v1/keystore/secrets`
}

export const createSecret = async (keystoreNewSecretCommand: KeystoreNewSecretCommand, options?: RequestInit): Promise<createSecretResponse> => {
  
  return customInstance<createSecretResponse>(getCreateSecretUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      keystoreNewSecretCommand,)
  }
);}




export const getCreateSecretMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ConflictResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSecret>>, TError,{data: BodyType<KeystoreNewSecretCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createSecret>>, TError,{data: BodyType<KeystoreNewSecretCommand>}, TContext> => {

const mutationKey = ['createSecret'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSecret>>, {data: BodyType<KeystoreNewSecretCommand>}> = (props) => {
          const {data} = props ?? {};

          return  createSecret(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSecretMutationResult = NonNullable<Awaited<ReturnType<typeof createSecret>>>
    export type CreateSecretMutationBody = BodyType<KeystoreNewSecretCommand>
    export type CreateSecretMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ConflictResponse | InternalServerErrorResponse>

    /**
 * @summary Create a secret
 */
export const useCreateSecret = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | ConflictResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSecret>>, TError,{data: BodyType<KeystoreNewSecretCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSecret>>,
        TError,
        {data: BodyType<KeystoreNewSecretCommand>},
        TContext
      > => {
      return useMutation(getCreateSecretMutationOptions(options), queryClient);
    }
    /**
 * @summary Read a secret's metadata
 */
export type getSecretResponse200 = {
  data: KeystoreSecretView
  status: 200
}

export type getSecretResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getSecretResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getSecretResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getSecretResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type getSecretResponseSuccess = (getSecretResponse200) & {
  headers: Headers;
};
export type getSecretResponseError = (getSecretResponse400 | getSecretResponse401 | getSecretResponse404 | getSecretResponse500) & {
  headers: Headers;
};

export type getSecretResponse = (getSecretResponseSuccess | getSecretResponseError)

export const getGetSecretUrl = (key: string,) => {


  

  return `/v1/keystore/secrets/${key}`
}

export const getSecret = async (key: string, options?: RequestInit): Promise<getSecretResponse> => {
  
  return customInstance<getSecretResponse>(getGetSecretUrl(key),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSecretInfiniteQueryKey = (key: string,) => {
    return [
    'infinite', `/v1/keystore/secrets/${key}`
    ] as const;
    }

export const getGetSecretQueryKey = (key: string,) => {
    return [
    `/v1/keystore/secrets/${key}`
    ] as const;
    }

    
export const getGetSecretInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getSecret>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>>(key: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSecretInfiniteQueryKey(key);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSecret>>> = ({ signal }) => getSecret(key, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(key),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetSecretInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getSecret>>>
export type GetSecretInfiniteQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>


export function useGetSecretInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSecret>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>>(
 key: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecret>>,
          TError,
          Awaited<ReturnType<typeof getSecret>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSecretInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSecret>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>>(
 key: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecret>>,
          TError,
          Awaited<ReturnType<typeof getSecret>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSecretInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSecret>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>>(
 key: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Read a secret's metadata
 */

export function useGetSecretInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSecret>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>>(
 key: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetSecretInfiniteQueryOptions(key,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetSecretQueryOptions = <TData = Awaited<ReturnType<typeof getSecret>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>>(key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSecretQueryKey(key);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSecret>>> = ({ signal }) => getSecret(key, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(key),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetSecretQueryResult = NonNullable<Awaited<ReturnType<typeof getSecret>>>
export type GetSecretQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>


export function useGetSecret<TData = Awaited<ReturnType<typeof getSecret>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>>(
 key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecret>>,
          TError,
          Awaited<ReturnType<typeof getSecret>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSecret<TData = Awaited<ReturnType<typeof getSecret>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecret>>,
          TError,
          Awaited<ReturnType<typeof getSecret>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSecret<TData = Awaited<ReturnType<typeof getSecret>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Read a secret's metadata
 */

export function useGetSecret<TData = Awaited<ReturnType<typeof getSecret>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecret>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetSecretQueryOptions(key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Rejected with 409 unless `expectedVersion` is the current version.
 * @summary Replace a secret's value
 */
export type updateSecretResponse200 = {
  data: KeystoreVersionResponse
  status: 200
}

export type updateSecretResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateSecretResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateSecretResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateSecretResponse409 = {
  data: ConflictResponse
  status: 409
}

export type updateSecretResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type updateSecretResponseSuccess = (updateSecretResponse200) & {
  headers: Headers;
};
export type updateSecretResponseError = (updateSecretResponse400 | updateSecretResponse401 | updateSecretResponse404 | updateSecretResponse409 | updateSecretResponse500) & {
  headers: Headers;
};

export type updateSecretResponse = (updateSecretResponseSuccess | updateSecretResponseError)

export const getUpdateSecretUrl = (key: string,) => {


  

  return `/v1/keystore/secrets/${key}`
}

export const updateSecret = async (key: string,
    keystoreEditSecretCommand: KeystoreEditSecretCommand, options?: RequestInit): Promise<updateSecretResponse> => {
  
  return customInstance<updateSecretResponse>(getUpdateSecretUrl(key),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      keystoreEditSecretCommand,)
  }
);}




export const getUpdateSecretMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSecret>>, TError,{key: string;data: BodyType<KeystoreEditSecretCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSecret>>, TError,{key: string;data: BodyType<KeystoreEditSecretCommand>}, TContext> => {

const mutationKey = ['updateSecret'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSecret>>, {key: string;data: BodyType<KeystoreEditSecretCommand>}> = (props) => {
          const {key,data} = props ?? {};

          return  updateSecret(key,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSecretMutationResult = NonNullable<Awaited<ReturnType<typeof updateSecret>>>
    export type UpdateSecretMutationBody = BodyType<KeystoreEditSecretCommand>
    export type UpdateSecretMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse | InternalServerErrorResponse>

    /**
 * @summary Replace a secret's value
 */
export const useUpdateSecret = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | ConflictResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSecret>>, TError,{key: string;data: BodyType<KeystoreEditSecretCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSecret>>,
        TError,
        {key: string;data: BodyType<KeystoreEditSecretCommand>},
        TContext
      > => {
      return useMutation(getUpdateSecretMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a secret
 */
export type deleteSecretResponse204 = {
  data: void
  status: 204
}

export type deleteSecretResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type deleteSecretResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteSecretResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteSecretResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type deleteSecretResponseSuccess = (deleteSecretResponse204) & {
  headers: Headers;
};
export type deleteSecretResponseError = (deleteSecretResponse400 | deleteSecretResponse401 | deleteSecretResponse404 | deleteSecretResponse500) & {
  headers: Headers;
};

export type deleteSecretResponse = (deleteSecretResponseSuccess | deleteSecretResponseError)

export const getDeleteSecretUrl = (key: string,) => {


  

  return `/v1/keystore/secrets/${key}`
}

export const deleteSecret = async (key: string, options?: RequestInit): Promise<deleteSecretResponse> => {
  
  return customInstance<deleteSecretResponse>(getDeleteSecretUrl(key),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteSecretMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSecret>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSecret>>, TError,{key: string}, TContext> => {

const mutationKey = ['deleteSecret'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSecret>>, {key: string}> = (props) => {
          const {key} = props ?? {};

          return  deleteSecret(key,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSecretMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSecret>>>
    
    export type DeleteSecretMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>

    /**
 * @summary Delete a secret
 */
export const useDeleteSecret = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSecret>>, TError,{key: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSecret>>,
        TError,
        {key: string},
        TContext
      > => {
      return useMutation(getDeleteSecretMutationOptions(options), queryClient);
    }
    