# ----------------------------
# Stage 1: Build Rust Backend (auth)
# ----------------------------
FROM rust:alpine3.23 AS backend-builder
WORKDIR /app

# Instalar dependencias de compilación para Alpine (musl)
RUN apk add --no-cache \
    musl-dev \
    build-base \
    protobuf \
    protobuf-dev \
    ca-certificates

# Copiamos todo el código fuente del backend
COPY . .

# Compilamos el binario de auth
RUN cargo build --release --manifest-path rainbow-auth/Cargo.toml

# ----------------------------
# Stage 2: Runtime minimal
# ----------------------------
FROM alpine:3.23
WORKDIR /app

# Librerías mínimas necesarias para ejecutar el binario
RUN apk add --no-cache libgcc libstdc++ ca-certificates

# Copiar el binario ya compilado
COPY --from=backend-builder /app/target/release/rainbow_auth /app/rainbow-auth

# Exponer puerto
EXPOSE 1500

# Variables de entorno
ENV RUST_LOG=info
ENV CONFIG_PATH=/app/static/environment/config/prod/core.consumer.yaml

# Comando de entrada
ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/app/rainbow-auth setup --env-file $CONFIG_PATH && /app/rainbow-auth start --env-file $CONFIG_PATH"]