name: "eunomia-ds-agent-provider"

services:
  provider-vault:
    image: hashicorp/vault:1.21
    container_name: provider-vault
    ports:
      - "8202:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./../../vault/provider/config:/vault/config
      - ./../../vault/provider/data:/vault/file
    environment:
      VAULT_CACERT: /vault/config/root-ca.pem
      VAULT_LOCAL_CONFIG: >
        {
          "storage": { "file": { "path": "/vault/file" } },
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_cert_file": "/vault/config/vault-cert.pem",
              "tls_key_file": "/vault/config/vault-key.pem",
              "tls_client_ca_file": "/vault/config/vault-ca.pem"
            }
          }],
          "ui": true,
          "api_addr": "https://127.0.0.1:8200",
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h"
        }
    command: server

  provider-db:
    container_name: "provider-db"
    image: "postgres"
    restart: always
    env_file:
      - ./../../static/environment/envs/provider.db.env
    ports:
      - "1400:5432"

  provider-redis:
    image: redis:alpine
    restart: always
    container_name: provider-redis
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --requirepass ds_core_provider_redis
      --user admin on >ds_core_provider_redis ~* +@all

  provider:
    container_name: provider
    image: rmenendez8/rainbow:v1.1.1
    # build:
    #   context: ../..
    #   dockerfile: deployment/prod/Dockerfile
    ports:
      - "1200:1200"
    volumes:
      - ./../../static:/app/static
      - ./../../vault/provider:/app/vault
    depends_on:
      - provider-db
      - provider-vault
      - provider-redis
    env_file:
      - ./../../static/environment/envs/provider.env
    environment:
      CONFIG_PATH: /app/static/environment/config/prod/core.provider.yaml
      RUST_BACKTRACE: full
