/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  GetAllVCRequestsParams,
  GetVcRequestDetails200,
  NotFoundResponse,
  OidcUri,
  PaginatedSentGrant,
  ReachAuthority,
  SentGrant,
  UnauthorizedResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List credential requests
 */
export type getAllVCRequestsResponse200 = {
  data: PaginatedSentGrant
  status: 200
}

export type getAllVCRequestsResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getAllVCRequestsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type getAllVCRequestsResponseSuccess = (getAllVCRequestsResponse200) & {
  headers: Headers;
};
export type getAllVCRequestsResponseError = (getAllVCRequestsResponse400 | getAllVCRequestsResponse401) & {
  headers: Headers;
};

export type getAllVCRequestsResponse = (getAllVCRequestsResponseSuccess | getAllVCRequestsResponseError)

export const getGetAllVCRequestsUrl = (params?: GetAllVCRequestsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/vc-request/all?${stringifiedParams}` : `/vc-request/all`
}

export const getAllVCRequests = async (params?: GetAllVCRequestsParams, options?: RequestInit): Promise<getAllVCRequestsResponse> => {
  
  return customInstance<getAllVCRequestsResponse>(getGetAllVCRequestsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAllVCRequestsInfiniteQueryKey = (params?: GetAllVCRequestsParams,) => {
    return [
    'infinite', `/vc-request/all`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetAllVCRequestsQueryKey = (params?: GetAllVCRequestsParams,) => {
    return [
    `/vc-request/all`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllVCRequestsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getAllVCRequests>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse>>(params?: GetAllVCRequestsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllVCRequestsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllVCRequests>>> = ({ signal }) => getAllVCRequests(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllVCRequestsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getAllVCRequests>>>
export type GetAllVCRequestsInfiniteQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse>


export function useGetAllVCRequestsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getAllVCRequests>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse>>(
 params: undefined |  GetAllVCRequestsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVCRequests>>,
          TError,
          Awaited<ReturnType<typeof getAllVCRequests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllVCRequestsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getAllVCRequests>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse>>(
 params?: GetAllVCRequestsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVCRequests>>,
          TError,
          Awaited<ReturnType<typeof getAllVCRequests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllVCRequestsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getAllVCRequests>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse>>(
 params?: GetAllVCRequestsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List credential requests
 */

export function useGetAllVCRequestsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getAllVCRequests>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse>>(
 params?: GetAllVCRequestsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllVCRequestsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetAllVCRequestsQueryOptions = <TData = Awaited<ReturnType<typeof getAllVCRequests>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse>>(params?: GetAllVCRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllVCRequestsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllVCRequests>>> = ({ signal }) => getAllVCRequests(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAllVCRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllVCRequests>>>
export type GetAllVCRequestsQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse>


export function useGetAllVCRequests<TData = Awaited<ReturnType<typeof getAllVCRequests>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse>>(
 params: undefined |  GetAllVCRequestsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVCRequests>>,
          TError,
          Awaited<ReturnType<typeof getAllVCRequests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllVCRequests<TData = Awaited<ReturnType<typeof getAllVCRequests>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse>>(
 params?: GetAllVCRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVCRequests>>,
          TError,
          Awaited<ReturnType<typeof getAllVCRequests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAllVCRequests<TData = Awaited<ReturnType<typeof getAllVCRequests>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse>>(
 params?: GetAllVCRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List credential requests
 */

export function useGetAllVCRequests<TData = Awaited<ReturnType<typeof getAllVCRequests>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse>>(
 params?: GetAllVCRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllVCRequests>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAllVCRequestsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Starts a GNAP credential request; with `auto` the OID4VP and OID4VCI steps run unattended.
 * @summary Request a credential from an authority
 */
export type begVcResponse200 = {
  data: void
  status: 200
}

export type begVcResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type begVcResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type begVcResponseSuccess = (begVcResponse200) & {
  headers: Headers;
};
export type begVcResponseError = (begVcResponse400 | begVcResponse401) & {
  headers: Headers;
};

export type begVcResponse = (begVcResponseSuccess | begVcResponseError)

export const getBegVcUrl = () => {


  

  return `/vc-request/beg`
}

export const begVc = async (reachAuthority: ReachAuthority, options?: RequestInit): Promise<begVcResponse> => {
  
  return customInstance<begVcResponse>(getBegVcUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reachAuthority,)
  }
);}




export const getBegVcMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof begVc>>, TError,{data: BodyType<ReachAuthority>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof begVc>>, TError,{data: BodyType<ReachAuthority>}, TContext> => {

const mutationKey = ['begVc'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof begVc>>, {data: BodyType<ReachAuthority>}> = (props) => {
          const {data} = props ?? {};

          return  begVc(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type BegVcMutationResult = NonNullable<Awaited<ReturnType<typeof begVc>>>
    export type BegVcMutationBody = BodyType<ReachAuthority>
    export type BegVcMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse>

    /**
 * @summary Request a credential from an authority
 */
export const useBegVc = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof begVc>>, TError,{data: BodyType<ReachAuthority>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof begVc>>,
        TError,
        {data: BodyType<ReachAuthority>},
        TContext
      > => {
      return useMutation(getBegVcMutationOptions(options), queryClient);
    }
    /**
 * @summary Redeem the credential offer of a request
 */
export type processVcRequestOid4vciResponse200 = {
  data: void
  status: 200
}

export type processVcRequestOid4vciResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type processVcRequestOid4vciResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type processVcRequestOid4vciResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type processVcRequestOid4vciResponseSuccess = (processVcRequestOid4vciResponse200) & {
  headers: Headers;
};
export type processVcRequestOid4vciResponseError = (processVcRequestOid4vciResponse400 | processVcRequestOid4vciResponse401 | processVcRequestOid4vciResponse404) & {
  headers: Headers;
};

export type processVcRequestOid4vciResponse = (processVcRequestOid4vciResponseSuccess | processVcRequestOid4vciResponseError)

export const getProcessVcRequestOid4vciUrl = (id: string,) => {


  

  return `/vc-request/oid4vci/${id}`
}

export const processVcRequestOid4vci = async (id: string,
    oidcUri: OidcUri, options?: RequestInit): Promise<processVcRequestOid4vciResponse> => {
  
  return customInstance<processVcRequestOid4vciResponse>(getProcessVcRequestOid4vciUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oidcUri,)
  }
);}




export const getProcessVcRequestOid4vciMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processVcRequestOid4vci>>, TError,{id: string;data: BodyType<OidcUri>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof processVcRequestOid4vci>>, TError,{id: string;data: BodyType<OidcUri>}, TContext> => {

const mutationKey = ['processVcRequestOid4vci'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof processVcRequestOid4vci>>, {id: string;data: BodyType<OidcUri>}> = (props) => {
          const {id,data} = props ?? {};

          return  processVcRequestOid4vci(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProcessVcRequestOid4vciMutationResult = NonNullable<Awaited<ReturnType<typeof processVcRequestOid4vci>>>
    export type ProcessVcRequestOid4vciMutationBody = BodyType<OidcUri>
    export type ProcessVcRequestOid4vciMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Redeem the credential offer of a request
 */
export const useProcessVcRequestOid4vci = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processVcRequestOid4vci>>, TError,{id: string;data: BodyType<OidcUri>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof processVcRequestOid4vci>>,
        TError,
        {id: string;data: BodyType<OidcUri>},
        TContext
      > => {
      return useMutation(getProcessVcRequestOid4vciMutationOptions(options), queryClient);
    }
    /**
 * @summary Answer the presentation request of a request
 */
export type processVcRequestOid4vpResponse200 = {
  data: void
  status: 200
}

export type processVcRequestOid4vpResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type processVcRequestOid4vpResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type processVcRequestOid4vpResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type processVcRequestOid4vpResponseSuccess = (processVcRequestOid4vpResponse200) & {
  headers: Headers;
};
export type processVcRequestOid4vpResponseError = (processVcRequestOid4vpResponse400 | processVcRequestOid4vpResponse401 | processVcRequestOid4vpResponse404) & {
  headers: Headers;
};

export type processVcRequestOid4vpResponse = (processVcRequestOid4vpResponseSuccess | processVcRequestOid4vpResponseError)

export const getProcessVcRequestOid4vpUrl = (id: string,) => {


  

  return `/vc-request/oid4vp/${id}`
}

export const processVcRequestOid4vp = async (id: string,
    oidcUri: OidcUri, options?: RequestInit): Promise<processVcRequestOid4vpResponse> => {
  
  return customInstance<processVcRequestOid4vpResponse>(getProcessVcRequestOid4vpUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oidcUri,)
  }
);}




export const getProcessVcRequestOid4vpMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processVcRequestOid4vp>>, TError,{id: string;data: BodyType<OidcUri>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof processVcRequestOid4vp>>, TError,{id: string;data: BodyType<OidcUri>}, TContext> => {

const mutationKey = ['processVcRequestOid4vp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof processVcRequestOid4vp>>, {id: string;data: BodyType<OidcUri>}> = (props) => {
          const {id,data} = props ?? {};

          return  processVcRequestOid4vp(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProcessVcRequestOid4vpMutationResult = NonNullable<Awaited<ReturnType<typeof processVcRequestOid4vp>>>
    export type ProcessVcRequestOid4vpMutationBody = BodyType<OidcUri>
    export type ProcessVcRequestOid4vpMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Answer the presentation request of a request
 */
export const useProcessVcRequestOid4vp = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processVcRequestOid4vp>>, TError,{id: string;data: BodyType<OidcUri>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof processVcRequestOid4vp>>,
        TError,
        {id: string;data: BodyType<OidcUri>},
        TContext
      > => {
      return useMutation(getProcessVcRequestOid4vpMutationOptions(options), queryClient);
    }
    /**
 * @summary Get a credential request
 */
export type getVcRequestByIdResponse200 = {
  data: SentGrant
  status: 200
}

export type getVcRequestByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getVcRequestByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type getVcRequestByIdResponseSuccess = (getVcRequestByIdResponse200) & {
  headers: Headers;
};
export type getVcRequestByIdResponseError = (getVcRequestByIdResponse401 | getVcRequestByIdResponse404) & {
  headers: Headers;
};

export type getVcRequestByIdResponse = (getVcRequestByIdResponseSuccess | getVcRequestByIdResponseError)

export const getGetVcRequestByIdUrl = (id: string,) => {


  

  return `/vc-request/${id}`
}

export const getVcRequestById = async (id: string, options?: RequestInit): Promise<getVcRequestByIdResponse> => {
  
  return customInstance<getVcRequestByIdResponse>(getGetVcRequestByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetVcRequestByIdInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/vc-request/${id}`
    ] as const;
    }

export const getGetVcRequestByIdQueryKey = (id: string,) => {
    return [
    `/vc-request/${id}`
    ] as const;
    }

    
export const getGetVcRequestByIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getVcRequestById>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVcRequestByIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVcRequestById>>> = ({ signal }) => getVcRequestById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetVcRequestByIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getVcRequestById>>>
export type GetVcRequestByIdInfiniteQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse>


export function useGetVcRequestByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVcRequestById>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVcRequestById>>,
          TError,
          Awaited<ReturnType<typeof getVcRequestById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVcRequestByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVcRequestById>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVcRequestById>>,
          TError,
          Awaited<ReturnType<typeof getVcRequestById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVcRequestByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVcRequestById>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get a credential request
 */

export function useGetVcRequestByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVcRequestById>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetVcRequestByIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetVcRequestByIdQueryOptions = <TData = Awaited<ReturnType<typeof getVcRequestById>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVcRequestByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVcRequestById>>> = ({ signal }) => getVcRequestById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetVcRequestByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getVcRequestById>>>
export type GetVcRequestByIdQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse>


export function useGetVcRequestById<TData = Awaited<ReturnType<typeof getVcRequestById>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVcRequestById>>,
          TError,
          Awaited<ReturnType<typeof getVcRequestById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVcRequestById<TData = Awaited<ReturnType<typeof getVcRequestById>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVcRequestById>>,
          TError,
          Awaited<ReturnType<typeof getVcRequestById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVcRequestById<TData = Awaited<ReturnType<typeof getVcRequestById>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get a credential request
 */

export function useGetVcRequestById<TData = Awaited<ReturnType<typeof getVcRequestById>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVcRequestById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetVcRequestByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Credential request with its interaction and verification
 */
export type getVcRequestDetailsResponse200 = {
  data: GetVcRequestDetails200
  status: 200
}

export type getVcRequestDetailsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getVcRequestDetailsResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type getVcRequestDetailsResponseSuccess = (getVcRequestDetailsResponse200) & {
  headers: Headers;
};
export type getVcRequestDetailsResponseError = (getVcRequestDetailsResponse401 | getVcRequestDetailsResponse404) & {
  headers: Headers;
};

export type getVcRequestDetailsResponse = (getVcRequestDetailsResponseSuccess | getVcRequestDetailsResponseError)

export const getGetVcRequestDetailsUrl = (id: string,) => {


  

  return `/vc-request/${id}/details`
}

export const getVcRequestDetails = async (id: string, options?: RequestInit): Promise<getVcRequestDetailsResponse> => {
  
  return customInstance<getVcRequestDetailsResponse>(getGetVcRequestDetailsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetVcRequestDetailsInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/vc-request/${id}/details`
    ] as const;
    }

export const getGetVcRequestDetailsQueryKey = (id: string,) => {
    return [
    `/vc-request/${id}/details`
    ] as const;
    }

    
export const getGetVcRequestDetailsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getVcRequestDetails>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVcRequestDetailsInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVcRequestDetails>>> = ({ signal }) => getVcRequestDetails(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetVcRequestDetailsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getVcRequestDetails>>>
export type GetVcRequestDetailsInfiniteQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse>


export function useGetVcRequestDetailsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVcRequestDetails>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVcRequestDetails>>,
          TError,
          Awaited<ReturnType<typeof getVcRequestDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVcRequestDetailsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVcRequestDetails>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVcRequestDetails>>,
          TError,
          Awaited<ReturnType<typeof getVcRequestDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVcRequestDetailsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVcRequestDetails>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Credential request with its interaction and verification
 */

export function useGetVcRequestDetailsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVcRequestDetails>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetVcRequestDetailsInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetVcRequestDetailsQueryOptions = <TData = Awaited<ReturnType<typeof getVcRequestDetails>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVcRequestDetailsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVcRequestDetails>>> = ({ signal }) => getVcRequestDetails(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetVcRequestDetailsQueryResult = NonNullable<Awaited<ReturnType<typeof getVcRequestDetails>>>
export type GetVcRequestDetailsQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse>


export function useGetVcRequestDetails<TData = Awaited<ReturnType<typeof getVcRequestDetails>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVcRequestDetails>>,
          TError,
          Awaited<ReturnType<typeof getVcRequestDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVcRequestDetails<TData = Awaited<ReturnType<typeof getVcRequestDetails>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVcRequestDetails>>,
          TError,
          Awaited<ReturnType<typeof getVcRequestDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetVcRequestDetails<TData = Awaited<ReturnType<typeof getVcRequestDetails>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Credential request with its interaction and verification
 */

export function useGetVcRequestDetails<TData = Awaited<ReturnType<typeof getVcRequestDetails>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVcRequestDetails>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetVcRequestDetailsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




