/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Rainbow Frontend Gateway API
 * OpenAPI specification for the Rainbow Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  OnboardProviderDto
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Onboard provider
 */
export type onboardProviderResponse200 = {
  data: string
  status: 200
}

export type onboardProviderResponse400 = {
  data: void
  status: 400
}

export type onboardProviderResponse401 = {
  data: void
  status: 401
}

export type onboardProviderResponse403 = {
  data: void
  status: 403
}

export type onboardProviderResponse404 = {
  data: void
  status: 404
}

export type onboardProviderResponse500 = {
  data: void
  status: 500
}
    
export type onboardProviderResponseSuccess = (onboardProviderResponse200) & {
  headers: Headers;
};
export type onboardProviderResponseError = (onboardProviderResponse400 | onboardProviderResponse401 | onboardProviderResponse403 | onboardProviderResponse404 | onboardProviderResponse500) & {
  headers: Headers;
};

export type onboardProviderResponse = (onboardProviderResponseSuccess | onboardProviderResponseError)

export const getOnboardProviderUrl = () => {


  

  return `/onboard/provider`
}

export const onboardProvider = async (onboardProviderDto: OnboardProviderDto, options?: RequestInit): Promise<onboardProviderResponse> => {
  
  return customInstance<onboardProviderResponse>(getOnboardProviderUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      onboardProviderDto,)
  }
);}




export const getOnboardProviderMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardProvider>>, TError,{data: BodyType<OnboardProviderDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof onboardProvider>>, TError,{data: BodyType<OnboardProviderDto>}, TContext> => {

const mutationKey = ['onboardProvider'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof onboardProvider>>, {data: BodyType<OnboardProviderDto>}> = (props) => {
          const {data} = props ?? {};

          return  onboardProvider(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type OnboardProviderMutationResult = NonNullable<Awaited<ReturnType<typeof onboardProvider>>>
    export type OnboardProviderMutationBody = BodyType<OnboardProviderDto>
    export type OnboardProviderMutationError = ErrorType<void>

    /**
 * @summary Onboard provider
 */
export const useOnboardProvider = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardProvider>>, TError,{data: BodyType<OnboardProviderDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof onboardProvider>>,
        TError,
        {data: BodyType<OnboardProviderDto>},
        TContext
      > => {
      return useMutation(getOnboardProviderMutationOptions(options), queryClient);
    }
    