/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  ForbiddenResponse,
  ProvisionedTenantDto,
  UnauthorizedResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Idempotent; existing main entities are kept.
 * @summary Give a tenant its main catalog and data service
 */
export type provisionTenantResponse200 = {
  data: ProvisionedTenantDto
  status: 200
}

export type provisionTenantResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type provisionTenantResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type provisionTenantResponse403 = {
  data: ForbiddenResponse
  status: 403
}
    
export type provisionTenantResponseSuccess = (provisionTenantResponse200) & {
  headers: Headers;
};
export type provisionTenantResponseError = (provisionTenantResponse400 | provisionTenantResponse401 | provisionTenantResponse403) & {
  headers: Headers;
};

export type provisionTenantResponse = (provisionTenantResponseSuccess | provisionTenantResponseError)

export const getProvisionTenantUrl = (tenantId: string,) => {


  

  return `/v1/catalog-agent/tenants/${tenantId}/provision`
}

export const provisionTenant = async (tenantId: string, options?: RequestInit): Promise<provisionTenantResponse> => {
  
  return customInstance<provisionTenantResponse>(getProvisionTenantUrl(tenantId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getProvisionTenantMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof provisionTenant>>, TError,{tenantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof provisionTenant>>, TError,{tenantId: string}, TContext> => {

const mutationKey = ['provisionTenant'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof provisionTenant>>, {tenantId: string}> = (props) => {
          const {tenantId} = props ?? {};

          return  provisionTenant(tenantId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProvisionTenantMutationResult = NonNullable<Awaited<ReturnType<typeof provisionTenant>>>
    
    export type ProvisionTenantMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>

    /**
 * @summary Give a tenant its main catalog and data service
 */
export const useProvisionTenant = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof provisionTenant>>, TError,{tenantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof provisionTenant>>,
        TError,
        {tenantId: string},
        TContext
      > => {
      return useMutation(getProvisionTenantMutationOptions(options), queryClient);
    }
    