/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  CreatePatCommand,
  CreatePatResponse,
  ForbiddenResponse,
  ListPersonalAccessTokensParams,
  NotFoundResponse,
  PaginatedPatRecord,
  UnauthorizedResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List personal access tokens
 */
export type listPersonalAccessTokensResponse200 = {
  data: PaginatedPatRecord
  status: 200
}

export type listPersonalAccessTokensResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type listPersonalAccessTokensResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type listPersonalAccessTokensResponse403 = {
  data: ForbiddenResponse
  status: 403
}
    
export type listPersonalAccessTokensResponseSuccess = (listPersonalAccessTokensResponse200) & {
  headers: Headers;
};
export type listPersonalAccessTokensResponseError = (listPersonalAccessTokensResponse400 | listPersonalAccessTokensResponse401 | listPersonalAccessTokensResponse403) & {
  headers: Headers;
};

export type listPersonalAccessTokensResponse = (listPersonalAccessTokensResponseSuccess | listPersonalAccessTokensResponseError)

export const getListPersonalAccessTokensUrl = (params?: ListPersonalAccessTokensParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/oauth/pats?${stringifiedParams}` : `/oauth/pats`
}

export const listPersonalAccessTokens = async (params?: ListPersonalAccessTokensParams, options?: RequestInit): Promise<listPersonalAccessTokensResponse> => {
  
  return customInstance<listPersonalAccessTokensResponse>(getListPersonalAccessTokensUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListPersonalAccessTokensInfiniteQueryKey = (params?: ListPersonalAccessTokensParams,) => {
    return [
    'infinite', `/oauth/pats`, ...(params ? [params] : [])
    ] as const;
    }

export const getListPersonalAccessTokensQueryKey = (params?: ListPersonalAccessTokensParams,) => {
    return [
    `/oauth/pats`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListPersonalAccessTokensInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof listPersonalAccessTokens>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(params?: ListPersonalAccessTokensParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPersonalAccessTokensInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPersonalAccessTokens>>> = ({ signal }) => listPersonalAccessTokens(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListPersonalAccessTokensInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listPersonalAccessTokens>>>
export type ListPersonalAccessTokensInfiniteQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>


export function useListPersonalAccessTokensInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listPersonalAccessTokens>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params: undefined |  ListPersonalAccessTokensParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPersonalAccessTokens>>,
          TError,
          Awaited<ReturnType<typeof listPersonalAccessTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListPersonalAccessTokensInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listPersonalAccessTokens>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: ListPersonalAccessTokensParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPersonalAccessTokens>>,
          TError,
          Awaited<ReturnType<typeof listPersonalAccessTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListPersonalAccessTokensInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listPersonalAccessTokens>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: ListPersonalAccessTokensParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List personal access tokens
 */

export function useListPersonalAccessTokensInfinite<TData = InfiniteData<Awaited<ReturnType<typeof listPersonalAccessTokens>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: ListPersonalAccessTokensParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListPersonalAccessTokensInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getListPersonalAccessTokensQueryOptions = <TData = Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(params?: ListPersonalAccessTokensParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPersonalAccessTokensQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPersonalAccessTokens>>> = ({ signal }) => listPersonalAccessTokens(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ListPersonalAccessTokensQueryResult = NonNullable<Awaited<ReturnType<typeof listPersonalAccessTokens>>>
export type ListPersonalAccessTokensQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>


export function useListPersonalAccessTokens<TData = Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params: undefined |  ListPersonalAccessTokensParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPersonalAccessTokens>>,
          TError,
          Awaited<ReturnType<typeof listPersonalAccessTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListPersonalAccessTokens<TData = Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: ListPersonalAccessTokensParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPersonalAccessTokens>>,
          TError,
          Awaited<ReturnType<typeof listPersonalAccessTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useListPersonalAccessTokens<TData = Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: ListPersonalAccessTokensParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List personal access tokens
 */

export function useListPersonalAccessTokens<TData = Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: ListPersonalAccessTokensParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPersonalAccessTokens>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getListPersonalAccessTokensQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * The token carries the caller's role. The raw token is only returned here.
 * @summary Create a personal access token
 */
export type createPersonalAccessTokenResponse201 = {
  data: CreatePatResponse
  status: 201
}

export type createPersonalAccessTokenResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createPersonalAccessTokenResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createPersonalAccessTokenResponse403 = {
  data: ForbiddenResponse
  status: 403
}
    
export type createPersonalAccessTokenResponseSuccess = (createPersonalAccessTokenResponse201) & {
  headers: Headers;
};
export type createPersonalAccessTokenResponseError = (createPersonalAccessTokenResponse400 | createPersonalAccessTokenResponse401 | createPersonalAccessTokenResponse403) & {
  headers: Headers;
};

export type createPersonalAccessTokenResponse = (createPersonalAccessTokenResponseSuccess | createPersonalAccessTokenResponseError)

export const getCreatePersonalAccessTokenUrl = () => {


  

  return `/oauth/pats`
}

export const createPersonalAccessToken = async (createPatCommand: CreatePatCommand, options?: RequestInit): Promise<createPersonalAccessTokenResponse> => {
  
  return customInstance<createPersonalAccessTokenResponse>(getCreatePersonalAccessTokenUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPatCommand,)
  }
);}




export const getCreatePersonalAccessTokenMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPersonalAccessToken>>, TError,{data: BodyType<CreatePatCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPersonalAccessToken>>, TError,{data: BodyType<CreatePatCommand>}, TContext> => {

const mutationKey = ['createPersonalAccessToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPersonalAccessToken>>, {data: BodyType<CreatePatCommand>}> = (props) => {
          const {data} = props ?? {};

          return  createPersonalAccessToken(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePersonalAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof createPersonalAccessToken>>>
    export type CreatePersonalAccessTokenMutationBody = BodyType<CreatePatCommand>
    export type CreatePersonalAccessTokenMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>

    /**
 * @summary Create a personal access token
 */
export const useCreatePersonalAccessToken = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPersonalAccessToken>>, TError,{data: BodyType<CreatePatCommand>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPersonalAccessToken>>,
        TError,
        {data: BodyType<CreatePatCommand>},
        TContext
      > => {
      return useMutation(getCreatePersonalAccessTokenMutationOptions(options), queryClient);
    }
    /**
 * @summary Revoke a personal access token
 */
export type revokePersonalAccessTokenResponse204 = {
  data: void
  status: 204
}

export type revokePersonalAccessTokenResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type revokePersonalAccessTokenResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type revokePersonalAccessTokenResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type revokePersonalAccessTokenResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type revokePersonalAccessTokenResponseSuccess = (revokePersonalAccessTokenResponse204) & {
  headers: Headers;
};
export type revokePersonalAccessTokenResponseError = (revokePersonalAccessTokenResponse400 | revokePersonalAccessTokenResponse401 | revokePersonalAccessTokenResponse403 | revokePersonalAccessTokenResponse404) & {
  headers: Headers;
};

export type revokePersonalAccessTokenResponse = (revokePersonalAccessTokenResponseSuccess | revokePersonalAccessTokenResponseError)

export const getRevokePersonalAccessTokenUrl = (patId: string,) => {


  

  return `/oauth/pats/${patId}`
}

export const revokePersonalAccessToken = async (patId: string, options?: RequestInit): Promise<revokePersonalAccessTokenResponse> => {
  
  return customInstance<revokePersonalAccessTokenResponse>(getRevokePersonalAccessTokenUrl(patId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getRevokePersonalAccessTokenMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokePersonalAccessToken>>, TError,{patId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokePersonalAccessToken>>, TError,{patId: string}, TContext> => {

const mutationKey = ['revokePersonalAccessToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokePersonalAccessToken>>, {patId: string}> = (props) => {
          const {patId} = props ?? {};

          return  revokePersonalAccessToken(patId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RevokePersonalAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof revokePersonalAccessToken>>>
    
    export type RevokePersonalAccessTokenMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>

    /**
 * @summary Revoke a personal access token
 */
export const useRevokePersonalAccessToken = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokePersonalAccessToken>>, TError,{patId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokePersonalAccessToken>>,
        TError,
        {patId: string},
        TContext
      > => {
      return useMutation(getRevokePersonalAccessTokenMutationOptions(options), queryClient);
    }
    