/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */

export interface EventEnvelope {
  id: string;
  tenant_id: string;
  topic: string;
  source_crate: string;
  schema_version: number;
  timestamp: string;
  /** URN shared by the events of one flow. */
  correlation_id?: string;
  /** W3C `traceparent` of the publishing span. */
  trace_context?: string;
  /** Event payload, any JSON value. */
  payload: unknown;
}
