/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */

export interface KeystoreEditSecretCommand {
  /** New secret value — any valid JSON */
  value: unknown;
  /**
   * Must match current version (optimistic locking)
   * @minimum 1
   */
  expectedVersion: number;
  description?: string | null;
}
