/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import type { KeystoreSecretViewValue } from './keystoreSecretViewValue';

export interface KeystoreSecretView {
  /** Path-style key */
  key: string;
  /** @minimum 1 */
  version: number;
  /** Always masked — never returns the real value */
  value: KeystoreSecretViewValue;
  description?: string | null;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
}
