/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import type { CursorParameter } from './cursorParameter';
import type { LimitParameter } from './limitParameter';
import type { ListDeadLettersStatus } from './listDeadLettersStatus';
import type { PageNumberParameter } from './pageNumberParameter';
import type { SortParameter } from './sortParameter';

export type ListDeadLettersParams = {
status?: ListDeadLettersStatus;
/**
 * @maximum 100
 */
limit?: LimitParameter;
/**
 * @minimum 1
 */
page?: PageNumberParameter;
/**
 * Opaque cursor from `nextCursor` of the previous page; takes precedence over `page`.
 */
cursor?: CursorParameter;
sort?: SortParameter;
};
