/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import type { InteractionMode } from './interactionMode';
import type { NewDataplaneTransferDtoEgressConfig } from './newDataplaneTransferDtoEgressConfig';
import type { NewDataplaneTransferDtoIngressConfig } from './newDataplaneTransferDtoIngressConfig';
import type { TransferRole } from './transferRole';
import type { TransferState } from './transferState';

export interface NewDataplaneTransferDto {
  /** @nullable */
  id?: string | null;
  transferProcessId: string;
  role: TransferRole;
  interactionMode: InteractionMode;
  state: TransferState;
  /** @nullable */
  connectorInstanceId?: string | null;
  ingressConfig: NewDataplaneTransferDtoIngressConfig;
  egressConfig: NewDataplaneTransferDtoEgressConfig;
}
