/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS-Agent Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */

export type OAuth2GrantType = typeof OAuth2GrantType[keyof typeof OAuth2GrantType];


export const OAuth2GrantType = {
  ClientCredentials: 'ClientCredentials',
  AuthorizationCode: 'AuthorizationCode',
} as const;
