/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import type { OdrlAgreementType } from './odrlAgreementType';
import type { OdrlDuty } from './odrlDuty';
import type { OdrlPermission } from './odrlPermission';
import type { OdrlProfile } from './odrlProfile';

export interface OdrlAgreement {
  '@id': string;
  '@type': OdrlAgreementType;
  profile?: OdrlProfile;
  permission?: OdrlPermission[];
  obligation?: OdrlDuty[];
  prohibition?: OdrlDuty[];
  target: string;
  assigner: string;
  assignee: string;
  /** @nullable */
  timestamp?: string | null;
  description?: string;
}
