/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS-Agent Frontend Gateway API
 * OpenAPI specification for the Eunomia DS-Agent Frontend Gateway.
The gateway proxies requests from the GUI to backend microservices.
All paths are prefixed with `/api` and routed by service prefix to the
corresponding microservice (catalog-agent, negotiation-agent, transfer-agent, auth-agent).

 * OpenAPI spec version: 1.0.0
 */
import type { LocalizedText } from './localizedText';
import type { OdrlPolicyInfo } from './odrlPolicyInfo';
import type { PolicyTemplateDtoParameters } from './policyTemplateDtoParameters';

export interface PolicyTemplateDto {
  id?: string;
  version?: string;
  date?: string;
  title?: LocalizedText;
  description?: LocalizedText;
  author?: string;
  content?: OdrlPolicyInfo;
  parameters?: PolicyTemplateDtoParameters;
}
