/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import type { SentGrantKind } from './sentGrantKind';
import type { SentGrantStatus } from './sentGrantStatus';
import type { VcTypeConfig } from './vcTypeConfig';

export interface SentGrant {
  id: string;
  tenant_id: string;
  participant_id: string;
  participant_nick: string;
  grant_endpoint: string;
  kind: SentGrantKind;
  status: SentGrantStatus;
  /** @nullable */
  token?: string | null;
  /** @nullable */
  vc_type_config?: VcTypeConfig[] | null;
  /** @nullable */
  vc_uri?: string | null;
  /** @nullable */
  as_assigned_id?: string | null;
  auto: boolean;
  created_at: string;
  /** @nullable */
  ended_at?: string | null;
}
