/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  DidDocument,
  InternalServerErrorResponse,
  NotFoundResponse,
  OidcUri,
  RegisterDidRequest,
  RegisterKeyRequest,
  UnauthorizedResponse,
  WalletCredential,
  WalletDid,
  WalletInfo,
  WalletKey
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Delete a credential
 */
export type deleteWalletCredentialResponse200 = {
  data: void
  status: 200
}

export type deleteWalletCredentialResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteWalletCredentialResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type deleteWalletCredentialResponseSuccess = (deleteWalletCredentialResponse200) & {
  headers: Headers;
};
export type deleteWalletCredentialResponseError = (deleteWalletCredentialResponse401 | deleteWalletCredentialResponse404) & {
  headers: Headers;
};

export type deleteWalletCredentialResponse = (deleteWalletCredentialResponseSuccess | deleteWalletCredentialResponseError)

export const getDeleteWalletCredentialUrl = (id: string,) => {


  

  return `/wallet/credential/${id}`
}

export const deleteWalletCredential = async (id: string, options?: RequestInit): Promise<deleteWalletCredentialResponse> => {
  
  return customInstance<deleteWalletCredentialResponse>(getDeleteWalletCredentialUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteWalletCredentialMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWalletCredential>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWalletCredential>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteWalletCredential'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWalletCredential>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteWalletCredential(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWalletCredentialMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWalletCredential>>>
    
    export type DeleteWalletCredentialMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Delete a credential
 */
export const useDeleteWalletCredential = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWalletCredential>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWalletCredential>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteWalletCredentialMutationOptions(options), queryClient);
    }
    /**
 * @summary The wallet's default DID
 */
export type getWalletDidStringResponse200 = {
  data: string
  status: 200
}

export type getWalletDidStringResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type getWalletDidStringResponseSuccess = (getWalletDidStringResponse200) & {
  headers: Headers;
};
export type getWalletDidStringResponseError = (getWalletDidStringResponse401) & {
  headers: Headers;
};

export type getWalletDidStringResponse = (getWalletDidStringResponseSuccess | getWalletDidStringResponseError)

export const getGetWalletDidStringUrl = () => {


  

  return `/wallet/did`
}

export const getWalletDidString = async ( options?: RequestInit): Promise<getWalletDidStringResponse> => {
  
  return customInstance<getWalletDidStringResponse>(getGetWalletDidStringUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetWalletDidStringInfiniteQueryKey = () => {
    return [
    'infinite', `/wallet/did`
    ] as const;
    }

export const getGetWalletDidStringQueryKey = () => {
    return [
    `/wallet/did`
    ] as const;
    }

    
export const getGetWalletDidStringInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getWalletDidString>>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletDidStringInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletDidString>>> = ({ signal }) => getWalletDidString({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWalletDidStringInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletDidString>>>
export type GetWalletDidStringInfiniteQueryError = ErrorType<UnauthorizedResponse>


export function useGetWalletDidStringInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletDidString>>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletDidString>>,
          TError,
          Awaited<ReturnType<typeof getWalletDidString>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletDidStringInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletDidString>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletDidString>>,
          TError,
          Awaited<ReturnType<typeof getWalletDidString>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletDidStringInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletDidString>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary The wallet's default DID
 */

export function useGetWalletDidStringInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletDidString>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWalletDidStringInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetWalletDidStringQueryOptions = <TData = Awaited<ReturnType<typeof getWalletDidString>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletDidStringQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletDidString>>> = ({ signal }) => getWalletDidString({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWalletDidStringQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletDidString>>>
export type GetWalletDidStringQueryError = ErrorType<UnauthorizedResponse>


export function useGetWalletDidString<TData = Awaited<ReturnType<typeof getWalletDidString>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletDidString>>,
          TError,
          Awaited<ReturnType<typeof getWalletDidString>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletDidString<TData = Awaited<ReturnType<typeof getWalletDidString>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletDidString>>,
          TError,
          Awaited<ReturnType<typeof getWalletDidString>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletDidString<TData = Awaited<ReturnType<typeof getWalletDidString>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary The wallet's default DID
 */

export function useGetWalletDidString<TData = Awaited<ReturnType<typeof getWalletDidString>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletDidString>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWalletDidStringQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a DID
 */
export type registerWalletDidResponse201 = {
  data: void
  status: 201
}

export type registerWalletDidResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type registerWalletDidResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type registerWalletDidResponseSuccess = (registerWalletDidResponse201) & {
  headers: Headers;
};
export type registerWalletDidResponseError = (registerWalletDidResponse400 | registerWalletDidResponse401) & {
  headers: Headers;
};

export type registerWalletDidResponse = (registerWalletDidResponseSuccess | registerWalletDidResponseError)

export const getRegisterWalletDidUrl = () => {


  

  return `/wallet/did`
}

export const registerWalletDid = async (registerDidRequest: RegisterDidRequest, options?: RequestInit): Promise<registerWalletDidResponse> => {
  
  return customInstance<registerWalletDidResponse>(getRegisterWalletDidUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerDidRequest,)
  }
);}




export const getRegisterWalletDidMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWalletDid>>, TError,{data: BodyType<RegisterDidRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerWalletDid>>, TError,{data: BodyType<RegisterDidRequest>}, TContext> => {

const mutationKey = ['registerWalletDid'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerWalletDid>>, {data: BodyType<RegisterDidRequest>}> = (props) => {
          const {data} = props ?? {};

          return  registerWalletDid(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterWalletDidMutationResult = NonNullable<Awaited<ReturnType<typeof registerWalletDid>>>
    export type RegisterWalletDidMutationBody = BodyType<RegisterDidRequest>
    export type RegisterWalletDidMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse>

    /**
 * @summary Create a DID
 */
export const useRegisterWalletDid = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWalletDid>>, TError,{data: BodyType<RegisterDidRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerWalletDid>>,
        TError,
        {data: BodyType<RegisterDidRequest>},
        TContext
      > => {
      return useMutation(getRegisterWalletDidMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a DID
 */
export type deleteWalletDidResponse200 = {
  data: void
  status: 200
}

export type deleteWalletDidResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteWalletDidResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type deleteWalletDidResponseSuccess = (deleteWalletDidResponse200) & {
  headers: Headers;
};
export type deleteWalletDidResponseError = (deleteWalletDidResponse401 | deleteWalletDidResponse404) & {
  headers: Headers;
};

export type deleteWalletDidResponse = (deleteWalletDidResponseSuccess | deleteWalletDidResponseError)

export const getDeleteWalletDidUrl = (id: string,) => {


  

  return `/wallet/did/${id}`
}

export const deleteWalletDid = async (id: string, options?: RequestInit): Promise<deleteWalletDidResponse> => {
  
  return customInstance<deleteWalletDidResponse>(getDeleteWalletDidUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteWalletDidMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWalletDid>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWalletDid>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteWalletDid'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWalletDid>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteWalletDid(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWalletDidMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWalletDid>>>
    
    export type DeleteWalletDidMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Delete a DID
 */
export const useDeleteWalletDid = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWalletDid>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWalletDid>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteWalletDidMutationOptions(options), queryClient);
    }
    /**
 * @summary Make a DID the default one
 */
export type setDefaultWalletDidResponse200 = {
  data: WalletDid
  status: 200
}

export type setDefaultWalletDidResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type setDefaultWalletDidResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type setDefaultWalletDidResponseSuccess = (setDefaultWalletDidResponse200) & {
  headers: Headers;
};
export type setDefaultWalletDidResponseError = (setDefaultWalletDidResponse401 | setDefaultWalletDidResponse404) & {
  headers: Headers;
};

export type setDefaultWalletDidResponse = (setDefaultWalletDidResponseSuccess | setDefaultWalletDidResponseError)

export const getSetDefaultWalletDidUrl = (id: string,) => {


  

  return `/wallet/did/${id}/default`
}

export const setDefaultWalletDid = async (id: string, options?: RequestInit): Promise<setDefaultWalletDidResponse> => {
  
  return customInstance<setDefaultWalletDidResponse>(getSetDefaultWalletDidUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getSetDefaultWalletDidMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setDefaultWalletDid>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof setDefaultWalletDid>>, TError,{id: string}, TContext> => {

const mutationKey = ['setDefaultWalletDid'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setDefaultWalletDid>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  setDefaultWalletDid(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SetDefaultWalletDidMutationResult = NonNullable<Awaited<ReturnType<typeof setDefaultWalletDid>>>
    
    export type SetDefaultWalletDidMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Make a DID the default one
 */
export const useSetDefaultWalletDid = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setDefaultWalletDid>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setDefaultWalletDid>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getSetDefaultWalletDidMutationOptions(options), queryClient);
    }
    /**
 * @summary Make a key the DID's default
 */
export type setDefaultKeyOfWalletDidResponse200 = {
  data: WalletDid
  status: 200
}

export type setDefaultKeyOfWalletDidResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type setDefaultKeyOfWalletDidResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type setDefaultKeyOfWalletDidResponseSuccess = (setDefaultKeyOfWalletDidResponse200) & {
  headers: Headers;
};
export type setDefaultKeyOfWalletDidResponseError = (setDefaultKeyOfWalletDidResponse401 | setDefaultKeyOfWalletDidResponse404) & {
  headers: Headers;
};

export type setDefaultKeyOfWalletDidResponse = (setDefaultKeyOfWalletDidResponseSuccess | setDefaultKeyOfWalletDidResponseError)

export const getSetDefaultKeyOfWalletDidUrl = (id: string,
    keyId: string,) => {


  

  return `/wallet/did/${id}/key/default/${keyId}`
}

export const setDefaultKeyOfWalletDid = async (id: string,
    keyId: string, options?: RequestInit): Promise<setDefaultKeyOfWalletDidResponse> => {
  
  return customInstance<setDefaultKeyOfWalletDidResponse>(getSetDefaultKeyOfWalletDidUrl(id,keyId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getSetDefaultKeyOfWalletDidMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setDefaultKeyOfWalletDid>>, TError,{id: string;keyId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof setDefaultKeyOfWalletDid>>, TError,{id: string;keyId: string}, TContext> => {

const mutationKey = ['setDefaultKeyOfWalletDid'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setDefaultKeyOfWalletDid>>, {id: string;keyId: string}> = (props) => {
          const {id,keyId} = props ?? {};

          return  setDefaultKeyOfWalletDid(id,keyId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SetDefaultKeyOfWalletDidMutationResult = NonNullable<Awaited<ReturnType<typeof setDefaultKeyOfWalletDid>>>
    
    export type SetDefaultKeyOfWalletDidMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Make a key the DID's default
 */
export const useSetDefaultKeyOfWalletDid = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setDefaultKeyOfWalletDid>>, TError,{id: string;keyId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setDefaultKeyOfWalletDid>>,
        TError,
        {id: string;keyId: string},
        TContext
      > => {
      return useMutation(getSetDefaultKeyOfWalletDidMutationOptions(options), queryClient);
    }
    /**
 * @summary Bind a key to a DID
 */
export type addKeyToWalletDidResponse200 = {
  data: WalletDid
  status: 200
}

export type addKeyToWalletDidResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type addKeyToWalletDidResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type addKeyToWalletDidResponseSuccess = (addKeyToWalletDidResponse200) & {
  headers: Headers;
};
export type addKeyToWalletDidResponseError = (addKeyToWalletDidResponse401 | addKeyToWalletDidResponse404) & {
  headers: Headers;
};

export type addKeyToWalletDidResponse = (addKeyToWalletDidResponseSuccess | addKeyToWalletDidResponseError)

export const getAddKeyToWalletDidUrl = (id: string,
    keyId: string,) => {


  

  return `/wallet/did/${id}/key/${keyId}`
}

export const addKeyToWalletDid = async (id: string,
    keyId: string, options?: RequestInit): Promise<addKeyToWalletDidResponse> => {
  
  return customInstance<addKeyToWalletDidResponse>(getAddKeyToWalletDidUrl(id,keyId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getAddKeyToWalletDidMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addKeyToWalletDid>>, TError,{id: string;keyId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addKeyToWalletDid>>, TError,{id: string;keyId: string}, TContext> => {

const mutationKey = ['addKeyToWalletDid'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addKeyToWalletDid>>, {id: string;keyId: string}> = (props) => {
          const {id,keyId} = props ?? {};

          return  addKeyToWalletDid(id,keyId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddKeyToWalletDidMutationResult = NonNullable<Awaited<ReturnType<typeof addKeyToWalletDid>>>
    
    export type AddKeyToWalletDidMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Bind a key to a DID
 */
export const useAddKeyToWalletDid = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addKeyToWalletDid>>, TError,{id: string;keyId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addKeyToWalletDid>>,
        TError,
        {id: string;keyId: string},
        TContext
      > => {
      return useMutation(getAddKeyToWalletDidMutationOptions(options), queryClient);
    }
    /**
 * @summary Unbind a key from a DID
 */
export type removeKeyFromWalletDidResponse200 = {
  data: WalletDid
  status: 200
}

export type removeKeyFromWalletDidResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type removeKeyFromWalletDidResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type removeKeyFromWalletDidResponseSuccess = (removeKeyFromWalletDidResponse200) & {
  headers: Headers;
};
export type removeKeyFromWalletDidResponseError = (removeKeyFromWalletDidResponse401 | removeKeyFromWalletDidResponse404) & {
  headers: Headers;
};

export type removeKeyFromWalletDidResponse = (removeKeyFromWalletDidResponseSuccess | removeKeyFromWalletDidResponseError)

export const getRemoveKeyFromWalletDidUrl = (id: string,
    keyId: string,) => {


  

  return `/wallet/did/${id}/key/${keyId}`
}

export const removeKeyFromWalletDid = async (id: string,
    keyId: string, options?: RequestInit): Promise<removeKeyFromWalletDidResponse> => {
  
  return customInstance<removeKeyFromWalletDidResponse>(getRemoveKeyFromWalletDidUrl(id,keyId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getRemoveKeyFromWalletDidMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeKeyFromWalletDid>>, TError,{id: string;keyId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeKeyFromWalletDid>>, TError,{id: string;keyId: string}, TContext> => {

const mutationKey = ['removeKeyFromWalletDid'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeKeyFromWalletDid>>, {id: string;keyId: string}> = (props) => {
          const {id,keyId} = props ?? {};

          return  removeKeyFromWalletDid(id,keyId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveKeyFromWalletDidMutationResult = NonNullable<Awaited<ReturnType<typeof removeKeyFromWalletDid>>>
    
    export type RemoveKeyFromWalletDidMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Unbind a key from a DID
 */
export const useRemoveKeyFromWalletDid = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeKeyFromWalletDid>>, TError,{id: string;keyId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeKeyFromWalletDid>>,
        TError,
        {id: string;keyId: string},
        TContext
      > => {
      return useMutation(getRemoveKeyFromWalletDidMutationOptions(options), queryClient);
    }
    /**
 * @summary Wallet information
 */
export type getWalletInfoResponse200 = {
  data: WalletInfo
  status: 200
}

export type getWalletInfoResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type getWalletInfoResponseSuccess = (getWalletInfoResponse200) & {
  headers: Headers;
};
export type getWalletInfoResponseError = (getWalletInfoResponse401) & {
  headers: Headers;
};

export type getWalletInfoResponse = (getWalletInfoResponseSuccess | getWalletInfoResponseError)

export const getGetWalletInfoUrl = () => {


  

  return `/wallet/info`
}

export const getWalletInfo = async ( options?: RequestInit): Promise<getWalletInfoResponse> => {
  
  return customInstance<getWalletInfoResponse>(getGetWalletInfoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetWalletInfoInfiniteQueryKey = () => {
    return [
    'infinite', `/wallet/info`
    ] as const;
    }

export const getGetWalletInfoQueryKey = () => {
    return [
    `/wallet/info`
    ] as const;
    }

    
export const getGetWalletInfoInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getWalletInfo>>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletInfoInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletInfo>>> = ({ signal }) => getWalletInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWalletInfoInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletInfo>>>
export type GetWalletInfoInfiniteQueryError = ErrorType<UnauthorizedResponse>


export function useGetWalletInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletInfo>>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletInfo>>,
          TError,
          Awaited<ReturnType<typeof getWalletInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletInfo>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletInfo>>,
          TError,
          Awaited<ReturnType<typeof getWalletInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletInfo>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Wallet information
 */

export function useGetWalletInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletInfo>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWalletInfoInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetWalletInfoQueryOptions = <TData = Awaited<ReturnType<typeof getWalletInfo>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletInfo>>> = ({ signal }) => getWalletInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWalletInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletInfo>>>
export type GetWalletInfoQueryError = ErrorType<UnauthorizedResponse>


export function useGetWalletInfo<TData = Awaited<ReturnType<typeof getWalletInfo>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletInfo>>,
          TError,
          Awaited<ReturnType<typeof getWalletInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletInfo<TData = Awaited<ReturnType<typeof getWalletInfo>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletInfo>>,
          TError,
          Awaited<ReturnType<typeof getWalletInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletInfo<TData = Awaited<ReturnType<typeof getWalletInfo>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Wallet information
 */

export function useGetWalletInfo<TData = Awaited<ReturnType<typeof getWalletInfo>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWalletInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Whether the wallet is linked
 */
export type isWalletLinkedResponse200 = {
  data: void
  status: 200
}

export type isWalletLinkedResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type isWalletLinkedResponse404 = {
  data: void
  status: 404
}
    
export type isWalletLinkedResponseSuccess = (isWalletLinkedResponse200) & {
  headers: Headers;
};
export type isWalletLinkedResponseError = (isWalletLinkedResponse401 | isWalletLinkedResponse404) & {
  headers: Headers;
};

export type isWalletLinkedResponse = (isWalletLinkedResponseSuccess | isWalletLinkedResponseError)

export const getIsWalletLinkedUrl = () => {


  

  return `/wallet/is-linked`
}

export const isWalletLinked = async ( options?: RequestInit): Promise<isWalletLinkedResponse> => {
  
  return customInstance<isWalletLinkedResponse>(getIsWalletLinkedUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getIsWalletLinkedInfiniteQueryKey = () => {
    return [
    'infinite', `/wallet/is-linked`
    ] as const;
    }

export const getIsWalletLinkedQueryKey = () => {
    return [
    `/wallet/is-linked`
    ] as const;
    }

    
export const getIsWalletLinkedInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof isWalletLinked>>>, TError = ErrorType<UnauthorizedResponse | void>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIsWalletLinkedInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof isWalletLinked>>> = ({ signal }) => isWalletLinked({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type IsWalletLinkedInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof isWalletLinked>>>
export type IsWalletLinkedInfiniteQueryError = ErrorType<UnauthorizedResponse | void>


export function useIsWalletLinkedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof isWalletLinked>>>, TError = ErrorType<UnauthorizedResponse | void>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof isWalletLinked>>,
          TError,
          Awaited<ReturnType<typeof isWalletLinked>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useIsWalletLinkedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof isWalletLinked>>>, TError = ErrorType<UnauthorizedResponse | void>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof isWalletLinked>>,
          TError,
          Awaited<ReturnType<typeof isWalletLinked>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useIsWalletLinkedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof isWalletLinked>>>, TError = ErrorType<UnauthorizedResponse | void>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Whether the wallet is linked
 */

export function useIsWalletLinkedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof isWalletLinked>>>, TError = ErrorType<UnauthorizedResponse | void>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getIsWalletLinkedInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getIsWalletLinkedQueryOptions = <TData = Awaited<ReturnType<typeof isWalletLinked>>, TError = ErrorType<UnauthorizedResponse | void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIsWalletLinkedQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof isWalletLinked>>> = ({ signal }) => isWalletLinked({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type IsWalletLinkedQueryResult = NonNullable<Awaited<ReturnType<typeof isWalletLinked>>>
export type IsWalletLinkedQueryError = ErrorType<UnauthorizedResponse | void>


export function useIsWalletLinked<TData = Awaited<ReturnType<typeof isWalletLinked>>, TError = ErrorType<UnauthorizedResponse | void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof isWalletLinked>>,
          TError,
          Awaited<ReturnType<typeof isWalletLinked>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useIsWalletLinked<TData = Awaited<ReturnType<typeof isWalletLinked>>, TError = ErrorType<UnauthorizedResponse | void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof isWalletLinked>>,
          TError,
          Awaited<ReturnType<typeof isWalletLinked>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useIsWalletLinked<TData = Awaited<ReturnType<typeof isWalletLinked>>, TError = ErrorType<UnauthorizedResponse | void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Whether the wallet is linked
 */

export function useIsWalletLinked<TData = Awaited<ReturnType<typeof isWalletLinked>>, TError = ErrorType<UnauthorizedResponse | void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof isWalletLinked>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getIsWalletLinkedQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * `kty` and `crv` are derived from the PEM.
 * @summary Import a private key
 */
export type registerWalletKeyResponse201 = {
  data: void
  status: 201
}

export type registerWalletKeyResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type registerWalletKeyResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type registerWalletKeyResponseSuccess = (registerWalletKeyResponse201) & {
  headers: Headers;
};
export type registerWalletKeyResponseError = (registerWalletKeyResponse400 | registerWalletKeyResponse401) & {
  headers: Headers;
};

export type registerWalletKeyResponse = (registerWalletKeyResponseSuccess | registerWalletKeyResponseError)

export const getRegisterWalletKeyUrl = () => {


  

  return `/wallet/key`
}

export const registerWalletKey = async (registerKeyRequest: RegisterKeyRequest, options?: RequestInit): Promise<registerWalletKeyResponse> => {
  
  return customInstance<registerWalletKeyResponse>(getRegisterWalletKeyUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerKeyRequest,)
  }
);}




export const getRegisterWalletKeyMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWalletKey>>, TError,{data: BodyType<RegisterKeyRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerWalletKey>>, TError,{data: BodyType<RegisterKeyRequest>}, TContext> => {

const mutationKey = ['registerWalletKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerWalletKey>>, {data: BodyType<RegisterKeyRequest>}> = (props) => {
          const {data} = props ?? {};

          return  registerWalletKey(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterWalletKeyMutationResult = NonNullable<Awaited<ReturnType<typeof registerWalletKey>>>
    export type RegisterWalletKeyMutationBody = BodyType<RegisterKeyRequest>
    export type RegisterWalletKeyMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse>

    /**
 * @summary Import a private key
 */
export const useRegisterWalletKey = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerWalletKey>>, TError,{data: BodyType<RegisterKeyRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerWalletKey>>,
        TError,
        {data: BodyType<RegisterKeyRequest>},
        TContext
      > => {
      return useMutation(getRegisterWalletKeyMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a key
 */
export type deleteWalletKeyResponse200 = {
  data: void
  status: 200
}

export type deleteWalletKeyResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteWalletKeyResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type deleteWalletKeyResponseSuccess = (deleteWalletKeyResponse200) & {
  headers: Headers;
};
export type deleteWalletKeyResponseError = (deleteWalletKeyResponse401 | deleteWalletKeyResponse404) & {
  headers: Headers;
};

export type deleteWalletKeyResponse = (deleteWalletKeyResponseSuccess | deleteWalletKeyResponseError)

export const getDeleteWalletKeyUrl = (id: string,) => {


  

  return `/wallet/key/${id}`
}

export const deleteWalletKey = async (id: string, options?: RequestInit): Promise<deleteWalletKeyResponse> => {
  
  return customInstance<deleteWalletKeyResponse>(getDeleteWalletKeyUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteWalletKeyMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWalletKey>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWalletKey>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteWalletKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWalletKey>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteWalletKey(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWalletKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWalletKey>>>
    
    export type DeleteWalletKeyMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Delete a key
 */
export const useDeleteWalletKey = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWalletKey>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWalletKey>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteWalletKeyMutationOptions(options), queryClient);
    }
    /**
 * @summary Keys of the wallet
 */
export type getWalletKeysResponse200 = {
  data: WalletKey[]
  status: 200
}

export type getWalletKeysResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type getWalletKeysResponseSuccess = (getWalletKeysResponse200) & {
  headers: Headers;
};
export type getWalletKeysResponseError = (getWalletKeysResponse401) & {
  headers: Headers;
};

export type getWalletKeysResponse = (getWalletKeysResponseSuccess | getWalletKeysResponseError)

export const getGetWalletKeysUrl = () => {


  

  return `/wallet/keys`
}

export const getWalletKeys = async ( options?: RequestInit): Promise<getWalletKeysResponse> => {
  
  return customInstance<getWalletKeysResponse>(getGetWalletKeysUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetWalletKeysInfiniteQueryKey = () => {
    return [
    'infinite', `/wallet/keys`
    ] as const;
    }

export const getGetWalletKeysQueryKey = () => {
    return [
    `/wallet/keys`
    ] as const;
    }

    
export const getGetWalletKeysInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getWalletKeys>>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletKeysInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletKeys>>> = ({ signal }) => getWalletKeys({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWalletKeysInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletKeys>>>
export type GetWalletKeysInfiniteQueryError = ErrorType<UnauthorizedResponse>


export function useGetWalletKeysInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletKeys>>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletKeys>>,
          TError,
          Awaited<ReturnType<typeof getWalletKeys>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletKeysInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletKeys>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletKeys>>,
          TError,
          Awaited<ReturnType<typeof getWalletKeys>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletKeysInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletKeys>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Keys of the wallet
 */

export function useGetWalletKeysInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletKeys>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWalletKeysInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetWalletKeysQueryOptions = <TData = Awaited<ReturnType<typeof getWalletKeys>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletKeysQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletKeys>>> = ({ signal }) => getWalletKeys({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWalletKeysQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletKeys>>>
export type GetWalletKeysQueryError = ErrorType<UnauthorizedResponse>


export function useGetWalletKeys<TData = Awaited<ReturnType<typeof getWalletKeys>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletKeys>>,
          TError,
          Awaited<ReturnType<typeof getWalletKeys>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletKeys<TData = Awaited<ReturnType<typeof getWalletKeys>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletKeys>>,
          TError,
          Awaited<ReturnType<typeof getWalletKeys>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletKeys<TData = Awaited<ReturnType<typeof getWalletKeys>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Keys of the wallet
 */

export function useGetWalletKeys<TData = Awaited<ReturnType<typeof getWalletKeys>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletKeys>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWalletKeysQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Link the wallet
 */
export type linkWalletResponse200 = {
  data: void
  status: 200
}

export type linkWalletResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type linkWalletResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type linkWalletResponseSuccess = (linkWalletResponse200) & {
  headers: Headers;
};
export type linkWalletResponseError = (linkWalletResponse401 | linkWalletResponse500) & {
  headers: Headers;
};

export type linkWalletResponse = (linkWalletResponseSuccess | linkWalletResponseError)

export const getLinkWalletUrl = () => {


  

  return `/wallet/link`
}

export const linkWallet = async ( options?: RequestInit): Promise<linkWalletResponse> => {
  
  return customInstance<linkWalletResponse>(getLinkWalletUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getLinkWalletMutationOptions = <TError = ErrorType<UnauthorizedResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkWallet>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof linkWallet>>, TError,void, TContext> => {

const mutationKey = ['linkWallet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof linkWallet>>, void> = () => {
          

          return  linkWallet(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LinkWalletMutationResult = NonNullable<Awaited<ReturnType<typeof linkWallet>>>
    
    export type LinkWalletMutationError = ErrorType<UnauthorizedResponse | InternalServerErrorResponse>

    /**
 * @summary Link the wallet
 */
export const useLinkWallet = <TError = ErrorType<UnauthorizedResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof linkWallet>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof linkWallet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLinkWalletMutationOptions(options), queryClient);
    }
    /**
 * @summary Redeem an OpenID4VCI credential offer
 */
export type processWalletOid4vciResponse200 = {
  data: void
  status: 200
}

export type processWalletOid4vciResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type processWalletOid4vciResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type processWalletOid4vciResponseSuccess = (processWalletOid4vciResponse200) & {
  headers: Headers;
};
export type processWalletOid4vciResponseError = (processWalletOid4vciResponse400 | processWalletOid4vciResponse401) & {
  headers: Headers;
};

export type processWalletOid4vciResponse = (processWalletOid4vciResponseSuccess | processWalletOid4vciResponseError)

export const getProcessWalletOid4vciUrl = () => {


  

  return `/wallet/oid4vci`
}

export const processWalletOid4vci = async (oidcUri: OidcUri, options?: RequestInit): Promise<processWalletOid4vciResponse> => {
  
  return customInstance<processWalletOid4vciResponse>(getProcessWalletOid4vciUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oidcUri,)
  }
);}




export const getProcessWalletOid4vciMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processWalletOid4vci>>, TError,{data: BodyType<OidcUri>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof processWalletOid4vci>>, TError,{data: BodyType<OidcUri>}, TContext> => {

const mutationKey = ['processWalletOid4vci'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof processWalletOid4vci>>, {data: BodyType<OidcUri>}> = (props) => {
          const {data} = props ?? {};

          return  processWalletOid4vci(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProcessWalletOid4vciMutationResult = NonNullable<Awaited<ReturnType<typeof processWalletOid4vci>>>
    export type ProcessWalletOid4vciMutationBody = BodyType<OidcUri>
    export type ProcessWalletOid4vciMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse>

    /**
 * @summary Redeem an OpenID4VCI credential offer
 */
export const useProcessWalletOid4vci = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processWalletOid4vci>>, TError,{data: BodyType<OidcUri>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof processWalletOid4vci>>,
        TError,
        {data: BodyType<OidcUri>},
        TContext
      > => {
      return useMutation(getProcessWalletOid4vciMutationOptions(options), queryClient);
    }
    /**
 * @summary Answer an OpenID4VP presentation request
 */
export type processWalletOid4vpResponse200 = {
  data: void
  status: 200
}

export type processWalletOid4vpResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type processWalletOid4vpResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type processWalletOid4vpResponseSuccess = (processWalletOid4vpResponse200) & {
  headers: Headers;
};
export type processWalletOid4vpResponseError = (processWalletOid4vpResponse400 | processWalletOid4vpResponse401) & {
  headers: Headers;
};

export type processWalletOid4vpResponse = (processWalletOid4vpResponseSuccess | processWalletOid4vpResponseError)

export const getProcessWalletOid4vpUrl = () => {


  

  return `/wallet/oid4vp`
}

export const processWalletOid4vp = async (oidcUri: OidcUri, options?: RequestInit): Promise<processWalletOid4vpResponse> => {
  
  return customInstance<processWalletOid4vpResponse>(getProcessWalletOid4vpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oidcUri,)
  }
);}




export const getProcessWalletOid4vpMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processWalletOid4vp>>, TError,{data: BodyType<OidcUri>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof processWalletOid4vp>>, TError,{data: BodyType<OidcUri>}, TContext> => {

const mutationKey = ['processWalletOid4vp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof processWalletOid4vp>>, {data: BodyType<OidcUri>}> = (props) => {
          const {data} = props ?? {};

          return  processWalletOid4vp(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProcessWalletOid4vpMutationResult = NonNullable<Awaited<ReturnType<typeof processWalletOid4vp>>>
    export type ProcessWalletOid4vpMutationBody = BodyType<OidcUri>
    export type ProcessWalletOid4vpMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse>

    /**
 * @summary Answer an OpenID4VP presentation request
 */
export const useProcessWalletOid4vp = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processWalletOid4vp>>, TError,{data: BodyType<OidcUri>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof processWalletOid4vp>>,
        TError,
        {data: BodyType<OidcUri>},
        TContext
      > => {
      return useMutation(getProcessWalletOid4vpMutationOptions(options), queryClient);
    }
    /**
 * @summary Credentials held
 */
export type getWalletCredentialsResponse200 = {
  data: WalletCredential[]
  status: 200
}

export type getWalletCredentialsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type getWalletCredentialsResponseSuccess = (getWalletCredentialsResponse200) & {
  headers: Headers;
};
export type getWalletCredentialsResponseError = (getWalletCredentialsResponse401) & {
  headers: Headers;
};

export type getWalletCredentialsResponse = (getWalletCredentialsResponseSuccess | getWalletCredentialsResponseError)

export const getGetWalletCredentialsUrl = () => {


  

  return `/wallet/vcs`
}

export const getWalletCredentials = async ( options?: RequestInit): Promise<getWalletCredentialsResponse> => {
  
  return customInstance<getWalletCredentialsResponse>(getGetWalletCredentialsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetWalletCredentialsInfiniteQueryKey = () => {
    return [
    'infinite', `/wallet/vcs`
    ] as const;
    }

export const getGetWalletCredentialsQueryKey = () => {
    return [
    `/wallet/vcs`
    ] as const;
    }

    
export const getGetWalletCredentialsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getWalletCredentials>>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletCredentialsInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletCredentials>>> = ({ signal }) => getWalletCredentials({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWalletCredentialsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletCredentials>>>
export type GetWalletCredentialsInfiniteQueryError = ErrorType<UnauthorizedResponse>


export function useGetWalletCredentialsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletCredentials>>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletCredentials>>,
          TError,
          Awaited<ReturnType<typeof getWalletCredentials>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletCredentialsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletCredentials>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletCredentials>>,
          TError,
          Awaited<ReturnType<typeof getWalletCredentials>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletCredentialsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletCredentials>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Credentials held
 */

export function useGetWalletCredentialsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletCredentials>>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWalletCredentialsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetWalletCredentialsQueryOptions = <TData = Awaited<ReturnType<typeof getWalletCredentials>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletCredentialsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletCredentials>>> = ({ signal }) => getWalletCredentials({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWalletCredentialsQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletCredentials>>>
export type GetWalletCredentialsQueryError = ErrorType<UnauthorizedResponse>


export function useGetWalletCredentials<TData = Awaited<ReturnType<typeof getWalletCredentials>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletCredentials>>,
          TError,
          Awaited<ReturnType<typeof getWalletCredentials>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletCredentials<TData = Awaited<ReturnType<typeof getWalletCredentials>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletCredentials>>,
          TError,
          Awaited<ReturnType<typeof getWalletCredentials>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletCredentials<TData = Awaited<ReturnType<typeof getWalletCredentials>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Credentials held
 */

export function useGetWalletCredentials<TData = Awaited<ReturnType<typeof getWalletCredentials>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletCredentials>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWalletCredentialsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary DID document of this agent (did:web resolution)
 */
export type getWalletDidResponse200 = {
  data: DidDocument
  status: 200
}

export type getWalletDidResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type getWalletDidResponseSuccess = (getWalletDidResponse200) & {
  headers: Headers;
};
export type getWalletDidResponseError = (getWalletDidResponse500) & {
  headers: Headers;
};

export type getWalletDidResponse = (getWalletDidResponseSuccess | getWalletDidResponseError)

export const getGetWalletDidUrl = () => {


  

  return `/well-known/did.json`
}

export const getWalletDid = async ( options?: RequestInit): Promise<getWalletDidResponse> => {
  
  return customInstance<getWalletDidResponse>(getGetWalletDidUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetWalletDidInfiniteQueryKey = () => {
    return [
    'infinite', `/well-known/did.json`
    ] as const;
    }

export const getGetWalletDidQueryKey = () => {
    return [
    `/well-known/did.json`
    ] as const;
    }

    
export const getGetWalletDidInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getWalletDid>>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletDidInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletDid>>> = ({ signal }) => getWalletDid({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWalletDidInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletDid>>>
export type GetWalletDidInfiniteQueryError = ErrorType<InternalServerErrorResponse>


export function useGetWalletDidInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletDid>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletDid>>,
          TError,
          Awaited<ReturnType<typeof getWalletDid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletDidInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletDid>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletDid>>,
          TError,
          Awaited<ReturnType<typeof getWalletDid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletDidInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletDid>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary DID document of this agent (did:web resolution)
 */

export function useGetWalletDidInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getWalletDid>>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWalletDidInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetWalletDidQueryOptions = <TData = Awaited<ReturnType<typeof getWalletDid>>, TError = ErrorType<InternalServerErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletDidQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletDid>>> = ({ signal }) => getWalletDid({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWalletDidQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletDid>>>
export type GetWalletDidQueryError = ErrorType<InternalServerErrorResponse>


export function useGetWalletDid<TData = Awaited<ReturnType<typeof getWalletDid>>, TError = ErrorType<InternalServerErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletDid>>,
          TError,
          Awaited<ReturnType<typeof getWalletDid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletDid<TData = Awaited<ReturnType<typeof getWalletDid>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletDid>>,
          TError,
          Awaited<ReturnType<typeof getWalletDid>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWalletDid<TData = Awaited<ReturnType<typeof getWalletDid>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary DID document of this agent (did:web resolution)
 */

export function useGetWalletDid<TData = Awaited<ReturnType<typeof getWalletDid>>, TError = ErrorType<InternalServerErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletDid>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWalletDidQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




