/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  NotFoundResponse,
  ParticipantDto,
  UnauthorizedResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Replace a participant's extra fields
 */
export type putMateByIdResponse200 = {
  data: ParticipantDto
  status: 200
}

export type putMateByIdResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type putMateByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type putMateByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type putMateByIdResponseSuccess = (putMateByIdResponse200) & {
  headers: Headers;
};
export type putMateByIdResponseError = (putMateByIdResponse400 | putMateByIdResponse401 | putMateByIdResponse404) & {
  headers: Headers;
};

export type putMateByIdResponse = (putMateByIdResponseSuccess | putMateByIdResponseError)

export const getPutMateByIdUrl = (id: string,) => {


  

  return `/mates/${id}`
}

export const putMateById = async (id: string,
    putMateByIdBody: unknown, options?: RequestInit): Promise<putMateByIdResponse> => {
  
  return customInstance<putMateByIdResponse>(getPutMateByIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putMateByIdBody,)
  }
);}




export const getPutMateByIdMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putMateById>>, TError,{id: string;data: BodyType<unknown>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putMateById>>, TError,{id: string;data: BodyType<unknown>}, TContext> => {

const mutationKey = ['putMateById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putMateById>>, {id: string;data: BodyType<unknown>}> = (props) => {
          const {id,data} = props ?? {};

          return  putMateById(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutMateByIdMutationResult = NonNullable<Awaited<ReturnType<typeof putMateById>>>
    export type PutMateByIdMutationBody = BodyType<unknown>
    export type PutMateByIdMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Replace a participant's extra fields
 */
export const usePutMateById = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putMateById>>, TError,{id: string;data: BodyType<unknown>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putMateById>>,
        TError,
        {id: string;data: BodyType<unknown>},
        TContext
      > => {
      return useMutation(getPutMateByIdMutationOptions(options), queryClient);
    }
    