[package]
name = "dataplane"
version = "0.3.8"
edition = "2021"

[lib]
name = "dataplane"
path = "src/lib.rs"


[dependencies]
common = { version = "0.3.1", path = "../common", default-features = true }
connector = { version = "0.3.1", path = "../connector", default-features = true }
keystore = { version = "0.1.0", path = "../keystore", default-features = true }

serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
reqwest = { workspace = true }
base64 = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
urn = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
hyper = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
ymir = { workspace = true }
redis = { workspace = true }
strum = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
