[package]
name = "common"
version = "0.3.8"
edition = "2021"

[lib]
name = "common"
path = "src/lib.rs"


[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
urn = { workspace = true }
mockall = { workspace = true }
json_to_table = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
serde_urlencoded = { workspace = true }
serde_norway = { workspace = true }
redis = { workspace = true }
ymir = { workspace = true }
http = "1.3.1"
sophia_api = "0.10"
sophia_jsonld = "0.10"
sophia_c14n = "0.10"
sophia_term = "0.10"
sophia_iri = "0.10"
json-syntax = "=0.9.6"
locspan = "0.7"
