/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  InternalServerErrorResponse,
  UnauthorizedResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Generate the Gaia-X self-attested credentials
 */
export type generateGaiaCredentialsResponse200 = {
  data: void
  status: 200
}

export type generateGaiaCredentialsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type generateGaiaCredentialsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}
    
export type generateGaiaCredentialsResponseSuccess = (generateGaiaCredentialsResponse200) & {
  headers: Headers;
};
export type generateGaiaCredentialsResponseError = (generateGaiaCredentialsResponse401 | generateGaiaCredentialsResponse500) & {
  headers: Headers;
};

export type generateGaiaCredentialsResponse = (generateGaiaCredentialsResponseSuccess | generateGaiaCredentialsResponseError)

export const getGenerateGaiaCredentialsUrl = () => {


  

  return `/gaia/generate`
}

export const generateGaiaCredentials = async ( options?: RequestInit): Promise<generateGaiaCredentialsResponse> => {
  
  return customInstance<generateGaiaCredentialsResponse>(getGenerateGaiaCredentialsUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getGenerateGaiaCredentialsMutationOptions = <TError = ErrorType<UnauthorizedResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateGaiaCredentials>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof generateGaiaCredentials>>, TError,void, TContext> => {

const mutationKey = ['generateGaiaCredentials'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateGaiaCredentials>>, void> = () => {
          

          return  generateGaiaCredentials(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateGaiaCredentialsMutationResult = NonNullable<Awaited<ReturnType<typeof generateGaiaCredentials>>>
    
    export type GenerateGaiaCredentialsMutationError = ErrorType<UnauthorizedResponse | InternalServerErrorResponse>

    /**
 * @summary Generate the Gaia-X self-attested credentials
 */
export const useGenerateGaiaCredentials = <TError = ErrorType<UnauthorizedResponse | InternalServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateGaiaCredentials>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateGaiaCredentials>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGenerateGaiaCredentialsMutationOptions(options), queryClient);
    }
    