/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  BatchRequests,
  CatalogDto,
  DatasetOfferingDto,
  DspCatalog,
  EditCatalogDto,
  ForbiddenResponse,
  GetCatalogsParams,
  NewCatalogDto,
  NewDatasetOfferingDto,
  NotFoundResponse,
  PaginatedCatalogDto,
  UnauthorizedResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List catalogs
 */
export type getCatalogsResponse200 = {
  data: PaginatedCatalogDto
  status: 200
}

export type getCatalogsResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getCatalogsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCatalogsResponse403 = {
  data: ForbiddenResponse
  status: 403
}
    
export type getCatalogsResponseSuccess = (getCatalogsResponse200) & {
  headers: Headers;
};
export type getCatalogsResponseError = (getCatalogsResponse400 | getCatalogsResponse401 | getCatalogsResponse403) & {
  headers: Headers;
};

export type getCatalogsResponse = (getCatalogsResponseSuccess | getCatalogsResponseError)

export const getGetCatalogsUrl = (params?: GetCatalogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/catalogs?${stringifiedParams}` : `/catalogs`
}

export const getCatalogs = async (params?: GetCatalogsParams, options?: RequestInit): Promise<getCatalogsResponse> => {
  
  return customInstance<getCatalogsResponse>(getGetCatalogsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetCatalogsInfiniteQueryKey = (params?: GetCatalogsParams,) => {
    return [
    'infinite', `/catalogs`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetCatalogsQueryKey = (params?: GetCatalogsParams,) => {
    return [
    `/catalogs`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetCatalogsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getCatalogs>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(params?: GetCatalogsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCatalogsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCatalogs>>> = ({ signal }) => getCatalogs(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCatalogsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getCatalogs>>>
export type GetCatalogsInfiniteQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>


export function useGetCatalogsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCatalogs>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params: undefined |  GetCatalogsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCatalogs>>,
          TError,
          Awaited<ReturnType<typeof getCatalogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCatalogsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCatalogs>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: GetCatalogsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCatalogs>>,
          TError,
          Awaited<ReturnType<typeof getCatalogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCatalogsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCatalogs>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: GetCatalogsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List catalogs
 */

export function useGetCatalogsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCatalogs>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: GetCatalogsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCatalogsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetCatalogsQueryOptions = <TData = Awaited<ReturnType<typeof getCatalogs>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(params?: GetCatalogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCatalogsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCatalogs>>> = ({ signal }) => getCatalogs(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCatalogsQueryResult = NonNullable<Awaited<ReturnType<typeof getCatalogs>>>
export type GetCatalogsQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>


export function useGetCatalogs<TData = Awaited<ReturnType<typeof getCatalogs>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params: undefined |  GetCatalogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCatalogs>>,
          TError,
          Awaited<ReturnType<typeof getCatalogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCatalogs<TData = Awaited<ReturnType<typeof getCatalogs>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: GetCatalogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCatalogs>>,
          TError,
          Awaited<ReturnType<typeof getCatalogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCatalogs<TData = Awaited<ReturnType<typeof getCatalogs>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: GetCatalogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List catalogs
 */

export function useGetCatalogs<TData = Awaited<ReturnType<typeof getCatalogs>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>>(
 params?: GetCatalogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCatalogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a catalog
 */
export type createCatalogResponse201 = {
  data: CatalogDto
  status: 201
}

export type createCatalogResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createCatalogResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createCatalogResponse403 = {
  data: ForbiddenResponse
  status: 403
}
    
export type createCatalogResponseSuccess = (createCatalogResponse201) & {
  headers: Headers;
};
export type createCatalogResponseError = (createCatalogResponse400 | createCatalogResponse401 | createCatalogResponse403) & {
  headers: Headers;
};

export type createCatalogResponse = (createCatalogResponseSuccess | createCatalogResponseError)

export const getCreateCatalogUrl = () => {


  

  return `/catalogs`
}

export const createCatalog = async (newCatalogDto: NewCatalogDto, options?: RequestInit): Promise<createCatalogResponse> => {
  
  return customInstance<createCatalogResponse>(getCreateCatalogUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newCatalogDto,)
  }
);}




export const getCreateCatalogMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCatalog>>, TError,{data: BodyType<NewCatalogDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCatalog>>, TError,{data: BodyType<NewCatalogDto>}, TContext> => {

const mutationKey = ['createCatalog'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCatalog>>, {data: BodyType<NewCatalogDto>}> = (props) => {
          const {data} = props ?? {};

          return  createCatalog(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCatalogMutationResult = NonNullable<Awaited<ReturnType<typeof createCatalog>>>
    export type CreateCatalogMutationBody = BodyType<NewCatalogDto>
    export type CreateCatalogMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>

    /**
 * @summary Create a catalog
 */
export const useCreateCatalog = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCatalog>>, TError,{data: BodyType<NewCatalogDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCatalog>>,
        TError,
        {data: BodyType<NewCatalogDto>},
        TContext
      > => {
      return useMutation(getCreateCatalogMutationOptions(options), queryClient);
    }
    /**
 * @summary Get several catalogs by id
 */
export type getBatchCatalogsResponse200 = {
  data: CatalogDto[]
  status: 200
}

export type getBatchCatalogsResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getBatchCatalogsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}
    
export type getBatchCatalogsResponseSuccess = (getBatchCatalogsResponse200) & {
  headers: Headers;
};
export type getBatchCatalogsResponseError = (getBatchCatalogsResponse400 | getBatchCatalogsResponse401) & {
  headers: Headers;
};

export type getBatchCatalogsResponse = (getBatchCatalogsResponseSuccess | getBatchCatalogsResponseError)

export const getGetBatchCatalogsUrl = () => {


  

  return `/catalogs/batch`
}

export const getBatchCatalogs = async (batchRequests: BatchRequests, options?: RequestInit): Promise<getBatchCatalogsResponse> => {
  
  return customInstance<getBatchCatalogsResponse>(getGetBatchCatalogsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      batchRequests,)
  }
);}




export const getGetBatchCatalogsMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getBatchCatalogs>>, TError,{data: BodyType<BatchRequests>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getBatchCatalogs>>, TError,{data: BodyType<BatchRequests>}, TContext> => {

const mutationKey = ['getBatchCatalogs'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getBatchCatalogs>>, {data: BodyType<BatchRequests>}> = (props) => {
          const {data} = props ?? {};

          return  getBatchCatalogs(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetBatchCatalogsMutationResult = NonNullable<Awaited<ReturnType<typeof getBatchCatalogs>>>
    export type GetBatchCatalogsMutationBody = BodyType<BatchRequests>
    export type GetBatchCatalogsMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse>

    /**
 * @summary Get several catalogs by id
 */
export const useGetBatchCatalogs = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getBatchCatalogs>>, TError,{data: BodyType<BatchRequests>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getBatchCatalogs>>,
        TError,
        {data: BodyType<BatchRequests>},
        TContext
      > => {
      return useMutation(getGetBatchCatalogsMutationOptions(options), queryClient);
    }
    /**
 * @summary The tenant's main catalog
 */
export type getMainCatalogsResponse200 = {
  data: CatalogDto
  status: 200
}

export type getMainCatalogsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMainCatalogsResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type getMainCatalogsResponseSuccess = (getMainCatalogsResponse200) & {
  headers: Headers;
};
export type getMainCatalogsResponseError = (getMainCatalogsResponse401 | getMainCatalogsResponse404) & {
  headers: Headers;
};

export type getMainCatalogsResponse = (getMainCatalogsResponseSuccess | getMainCatalogsResponseError)

export const getGetMainCatalogsUrl = () => {


  

  return `/catalogs/main`
}

export const getMainCatalogs = async ( options?: RequestInit): Promise<getMainCatalogsResponse> => {
  
  return customInstance<getMainCatalogsResponse>(getGetMainCatalogsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMainCatalogsInfiniteQueryKey = () => {
    return [
    'infinite', `/catalogs/main`
    ] as const;
    }

export const getGetMainCatalogsQueryKey = () => {
    return [
    `/catalogs/main`
    ] as const;
    }

    
export const getGetMainCatalogsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getMainCatalogs>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMainCatalogsInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMainCatalogs>>> = ({ signal }) => getMainCatalogs({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetMainCatalogsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getMainCatalogs>>>
export type GetMainCatalogsInfiniteQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse>


export function useGetMainCatalogsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getMainCatalogs>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMainCatalogs>>,
          TError,
          Awaited<ReturnType<typeof getMainCatalogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMainCatalogsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getMainCatalogs>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMainCatalogs>>,
          TError,
          Awaited<ReturnType<typeof getMainCatalogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMainCatalogsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getMainCatalogs>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary The tenant's main catalog
 */

export function useGetMainCatalogsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getMainCatalogs>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetMainCatalogsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetMainCatalogsQueryOptions = <TData = Awaited<ReturnType<typeof getMainCatalogs>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMainCatalogsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMainCatalogs>>> = ({ signal }) => getMainCatalogs({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetMainCatalogsQueryResult = NonNullable<Awaited<ReturnType<typeof getMainCatalogs>>>
export type GetMainCatalogsQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse>


export function useGetMainCatalogs<TData = Awaited<ReturnType<typeof getMainCatalogs>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMainCatalogs>>,
          TError,
          Awaited<ReturnType<typeof getMainCatalogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMainCatalogs<TData = Awaited<ReturnType<typeof getMainCatalogs>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMainCatalogs>>,
          TError,
          Awaited<ReturnType<typeof getMainCatalogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetMainCatalogs<TData = Awaited<ReturnType<typeof getMainCatalogs>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary The tenant's main catalog
 */

export function useGetMainCatalogs<TData = Awaited<ReturnType<typeof getMainCatalogs>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMainCatalogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetMainCatalogsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create the tenant's main catalog
 */
export type createMainCatalogResponse201 = {
  data: CatalogDto
  status: 201
}

export type createMainCatalogResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createMainCatalogResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createMainCatalogResponse403 = {
  data: ForbiddenResponse
  status: 403
}
    
export type createMainCatalogResponseSuccess = (createMainCatalogResponse201) & {
  headers: Headers;
};
export type createMainCatalogResponseError = (createMainCatalogResponse400 | createMainCatalogResponse401 | createMainCatalogResponse403) & {
  headers: Headers;
};

export type createMainCatalogResponse = (createMainCatalogResponseSuccess | createMainCatalogResponseError)

export const getCreateMainCatalogUrl = () => {


  

  return `/catalogs/main`
}

export const createMainCatalog = async (newCatalogDto: NewCatalogDto, options?: RequestInit): Promise<createMainCatalogResponse> => {
  
  return customInstance<createMainCatalogResponse>(getCreateMainCatalogUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newCatalogDto,)
  }
);}




export const getCreateMainCatalogMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMainCatalog>>, TError,{data: BodyType<NewCatalogDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createMainCatalog>>, TError,{data: BodyType<NewCatalogDto>}, TContext> => {

const mutationKey = ['createMainCatalog'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMainCatalog>>, {data: BodyType<NewCatalogDto>}> = (props) => {
          const {data} = props ?? {};

          return  createMainCatalog(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMainCatalogMutationResult = NonNullable<Awaited<ReturnType<typeof createMainCatalog>>>
    export type CreateMainCatalogMutationBody = BodyType<NewCatalogDto>
    export type CreateMainCatalogMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>

    /**
 * @summary Create the tenant's main catalog
 */
export const useCreateMainCatalog = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMainCatalog>>, TError,{data: BodyType<NewCatalogDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMainCatalog>>,
        TError,
        {data: BodyType<NewCatalogDto>},
        TContext
      > => {
      return useMutation(getCreateMainCatalogMutationOptions(options), queryClient);
    }
    /**
 * @summary Get a catalog
 */
export type getCatalogByIdResponse200 = {
  data: CatalogDto
  status: 200
}

export type getCatalogByIdResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getCatalogByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCatalogByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type getCatalogByIdResponseSuccess = (getCatalogByIdResponse200) & {
  headers: Headers;
};
export type getCatalogByIdResponseError = (getCatalogByIdResponse400 | getCatalogByIdResponse401 | getCatalogByIdResponse404) & {
  headers: Headers;
};

export type getCatalogByIdResponse = (getCatalogByIdResponseSuccess | getCatalogByIdResponseError)

export const getGetCatalogByIdUrl = (id: string,) => {


  

  return `/catalogs/${id}`
}

export const getCatalogById = async (id: string, options?: RequestInit): Promise<getCatalogByIdResponse> => {
  
  return customInstance<getCatalogByIdResponse>(getGetCatalogByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetCatalogByIdInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/catalogs/${id}`
    ] as const;
    }

export const getGetCatalogByIdQueryKey = (id: string,) => {
    return [
    `/catalogs/${id}`
    ] as const;
    }

    
export const getGetCatalogByIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getCatalogById>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCatalogByIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCatalogById>>> = ({ signal }) => getCatalogById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCatalogByIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getCatalogById>>>
export type GetCatalogByIdInfiniteQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>


export function useGetCatalogByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCatalogById>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCatalogById>>,
          TError,
          Awaited<ReturnType<typeof getCatalogById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCatalogByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCatalogById>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCatalogById>>,
          TError,
          Awaited<ReturnType<typeof getCatalogById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCatalogByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCatalogById>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get a catalog
 */

export function useGetCatalogByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getCatalogById>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCatalogByIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetCatalogByIdQueryOptions = <TData = Awaited<ReturnType<typeof getCatalogById>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCatalogByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCatalogById>>> = ({ signal }) => getCatalogById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCatalogByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCatalogById>>>
export type GetCatalogByIdQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>


export function useGetCatalogById<TData = Awaited<ReturnType<typeof getCatalogById>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCatalogById>>,
          TError,
          Awaited<ReturnType<typeof getCatalogById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCatalogById<TData = Awaited<ReturnType<typeof getCatalogById>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCatalogById>>,
          TError,
          Awaited<ReturnType<typeof getCatalogById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCatalogById<TData = Awaited<ReturnType<typeof getCatalogById>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get a catalog
 */

export function useGetCatalogById<TData = Awaited<ReturnType<typeof getCatalogById>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCatalogById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCatalogByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update a catalog
 */
export type updateCatalogResponse202 = {
  data: CatalogDto
  status: 202
}

export type updateCatalogResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateCatalogResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateCatalogResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateCatalogResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type updateCatalogResponseSuccess = (updateCatalogResponse202) & {
  headers: Headers;
};
export type updateCatalogResponseError = (updateCatalogResponse400 | updateCatalogResponse401 | updateCatalogResponse403 | updateCatalogResponse404) & {
  headers: Headers;
};

export type updateCatalogResponse = (updateCatalogResponseSuccess | updateCatalogResponseError)

export const getUpdateCatalogUrl = (id: string,) => {


  

  return `/catalogs/${id}`
}

export const updateCatalog = async (id: string,
    editCatalogDto: EditCatalogDto, options?: RequestInit): Promise<updateCatalogResponse> => {
  
  return customInstance<updateCatalogResponse>(getUpdateCatalogUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editCatalogDto,)
  }
);}




export const getUpdateCatalogMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCatalog>>, TError,{id: string;data: BodyType<EditCatalogDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCatalog>>, TError,{id: string;data: BodyType<EditCatalogDto>}, TContext> => {

const mutationKey = ['updateCatalog'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCatalog>>, {id: string;data: BodyType<EditCatalogDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCatalog(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCatalogMutationResult = NonNullable<Awaited<ReturnType<typeof updateCatalog>>>
    export type UpdateCatalogMutationBody = BodyType<EditCatalogDto>
    export type UpdateCatalogMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>

    /**
 * @summary Update a catalog
 */
export const useUpdateCatalog = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCatalog>>, TError,{id: string;data: BodyType<EditCatalogDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCatalog>>,
        TError,
        {id: string;data: BodyType<EditCatalogDto>},
        TContext
      > => {
      return useMutation(getUpdateCatalogMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a catalog
 */
export type deleteCatalogResponse202 = {
  data: void
  status: 202
}

export type deleteCatalogResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type deleteCatalogResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteCatalogResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteCatalogResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type deleteCatalogResponseSuccess = (deleteCatalogResponse202) & {
  headers: Headers;
};
export type deleteCatalogResponseError = (deleteCatalogResponse400 | deleteCatalogResponse401 | deleteCatalogResponse403 | deleteCatalogResponse404) & {
  headers: Headers;
};

export type deleteCatalogResponse = (deleteCatalogResponseSuccess | deleteCatalogResponseError)

export const getDeleteCatalogUrl = (id: string,) => {


  

  return `/catalogs/${id}`
}

export const deleteCatalog = async (id: string, options?: RequestInit): Promise<deleteCatalogResponse> => {
  
  return customInstance<deleteCatalogResponse>(getDeleteCatalogUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteCatalogMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCatalog>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCatalog>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteCatalog'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCatalog>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteCatalog(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCatalogMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCatalog>>>
    
    export type DeleteCatalogMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>

    /**
 * @summary Delete a catalog
 */
export const useDeleteCatalog = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCatalog>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCatalog>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteCatalogMutationOptions(options), queryClient);
    }
    /**
 * Without `dataset.catalogId` the dataset goes to the tenant's main catalog; without
`distribution.accessServiceId` the distribution uses the main data service.

 * @summary Publish a dataset with its distribution and policy
 */
export type createDatasetOfferingResponse201 = {
  data: DatasetOfferingDto
  status: 201
}

export type createDatasetOfferingResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createDatasetOfferingResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createDatasetOfferingResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createDatasetOfferingResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type createDatasetOfferingResponseSuccess = (createDatasetOfferingResponse201) & {
  headers: Headers;
};
export type createDatasetOfferingResponseError = (createDatasetOfferingResponse400 | createDatasetOfferingResponse401 | createDatasetOfferingResponse403 | createDatasetOfferingResponse404) & {
  headers: Headers;
};

export type createDatasetOfferingResponse = (createDatasetOfferingResponseSuccess | createDatasetOfferingResponseError)

export const getCreateDatasetOfferingUrl = () => {


  

  return `/dataset-offerings`
}

export const createDatasetOffering = async (newDatasetOfferingDto: NewDatasetOfferingDto, options?: RequestInit): Promise<createDatasetOfferingResponse> => {
  
  return customInstance<createDatasetOfferingResponse>(getCreateDatasetOfferingUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newDatasetOfferingDto,)
  }
);}




export const getCreateDatasetOfferingMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDatasetOffering>>, TError,{data: BodyType<NewDatasetOfferingDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDatasetOffering>>, TError,{data: BodyType<NewDatasetOfferingDto>}, TContext> => {

const mutationKey = ['createDatasetOffering'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDatasetOffering>>, {data: BodyType<NewDatasetOfferingDto>}> = (props) => {
          const {data} = props ?? {};

          return  createDatasetOffering(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDatasetOfferingMutationResult = NonNullable<Awaited<ReturnType<typeof createDatasetOffering>>>
    export type CreateDatasetOfferingMutationBody = BodyType<NewDatasetOfferingDto>
    export type CreateDatasetOfferingMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>

    /**
 * @summary Publish a dataset with its distribution and policy
 */
export const useCreateDatasetOffering = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDatasetOffering>>, TError,{data: BodyType<NewDatasetOfferingDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDatasetOffering>>,
        TError,
        {data: BodyType<NewDatasetOfferingDto>},
        TContext
      > => {
      return useMutation(getCreateDatasetOfferingMutationOptions(options), queryClient);
    }
    /**
 * @summary Cached catalog of one peer
 */
export type getPeerCatalogResponse200 = {
  data: DspCatalog
  status: 200
}

export type getPeerCatalogResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getPeerCatalogResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type getPeerCatalogResponseSuccess = (getPeerCatalogResponse200) & {
  headers: Headers;
};
export type getPeerCatalogResponseError = (getPeerCatalogResponse401 | getPeerCatalogResponse404) & {
  headers: Headers;
};

export type getPeerCatalogResponse = (getPeerCatalogResponseSuccess | getPeerCatalogResponseError)

export const getGetPeerCatalogUrl = (peerId: string,) => {


  

  return `/peer-catalogs/${peerId}`
}

export const getPeerCatalog = async (peerId: string, options?: RequestInit): Promise<getPeerCatalogResponse> => {
  
  return customInstance<getPeerCatalogResponse>(getGetPeerCatalogUrl(peerId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPeerCatalogInfiniteQueryKey = (peerId: string,) => {
    return [
    'infinite', `/peer-catalogs/${peerId}`
    ] as const;
    }

export const getGetPeerCatalogQueryKey = (peerId: string,) => {
    return [
    `/peer-catalogs/${peerId}`
    ] as const;
    }

    
export const getGetPeerCatalogInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getPeerCatalog>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(peerId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPeerCatalogInfiniteQueryKey(peerId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPeerCatalog>>> = ({ signal }) => getPeerCatalog(peerId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(peerId),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPeerCatalogInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getPeerCatalog>>>
export type GetPeerCatalogInfiniteQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse>


export function useGetPeerCatalogInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPeerCatalog>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 peerId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPeerCatalog>>,
          TError,
          Awaited<ReturnType<typeof getPeerCatalog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPeerCatalogInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPeerCatalog>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 peerId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPeerCatalog>>,
          TError,
          Awaited<ReturnType<typeof getPeerCatalog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPeerCatalogInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPeerCatalog>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 peerId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Cached catalog of one peer
 */

export function useGetPeerCatalogInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPeerCatalog>>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 peerId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPeerCatalogInfiniteQueryOptions(peerId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetPeerCatalogQueryOptions = <TData = Awaited<ReturnType<typeof getPeerCatalog>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(peerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPeerCatalogQueryKey(peerId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPeerCatalog>>> = ({ signal }) => getPeerCatalog(peerId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(peerId),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetPeerCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof getPeerCatalog>>>
export type GetPeerCatalogQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse>


export function useGetPeerCatalog<TData = Awaited<ReturnType<typeof getPeerCatalog>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 peerId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPeerCatalog>>,
          TError,
          Awaited<ReturnType<typeof getPeerCatalog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPeerCatalog<TData = Awaited<ReturnType<typeof getPeerCatalog>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 peerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPeerCatalog>>,
          TError,
          Awaited<ReturnType<typeof getPeerCatalog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetPeerCatalog<TData = Awaited<ReturnType<typeof getPeerCatalog>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 peerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Cached catalog of one peer
 */

export function useGetPeerCatalog<TData = Awaited<ReturnType<typeof getPeerCatalog>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 peerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPeerCatalog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetPeerCatalogQueryOptions(peerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




