/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Eunomia DS Frontend Gateway API
 * Admin API as the GUI sees it through the gateway agent (`crates/bff`). The gateway
answers under `/admin/api` and forwards each path prefix to the agent that owns it
(`catalogs` to the catalog agent, `negotiations` to the negotiation agent, `v1` to
`/api/v1` of the core agent, and so on); the bearer token and `x-tenant-id` are
forwarded and checked there. Mirrors the per-agent specs in this folder; operation ids
and tags match the orval client in `gui/shared/src/data/orval`, and deprecated operations
are calls the GUI still makes to routes the backend no longer serves.

 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  ConnectorInstanceDto,
  ConnectorInstantiationDto,
  ForbiddenResponse,
  NotFoundResponse,
  UnauthorizedResponse
} from '.././model';

import { customInstance } from '../../orval-mutator';
import type { ErrorType , BodyType } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Validates the parameters against the template, adds system parameters, resolves every
placeholder and stores the result. With `dryRun` the instance is resolved but not stored.

 * @summary Create or replace the instance of a distribution
 */
export type upsertConnectorInstanceResponse200 = {
  data: ConnectorInstanceDto
  status: 200
}

export type upsertConnectorInstanceResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type upsertConnectorInstanceResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type upsertConnectorInstanceResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type upsertConnectorInstanceResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type upsertConnectorInstanceResponseSuccess = (upsertConnectorInstanceResponse200) & {
  headers: Headers;
};
export type upsertConnectorInstanceResponseError = (upsertConnectorInstanceResponse400 | upsertConnectorInstanceResponse401 | upsertConnectorInstanceResponse403 | upsertConnectorInstanceResponse404) & {
  headers: Headers;
};

export type upsertConnectorInstanceResponse = (upsertConnectorInstanceResponseSuccess | upsertConnectorInstanceResponseError)

export const getUpsertConnectorInstanceUrl = () => {


  

  return `/connector/instances`
}

export const upsertConnectorInstance = async (connectorInstantiationDto: ConnectorInstantiationDto, options?: RequestInit): Promise<upsertConnectorInstanceResponse> => {
  
  return customInstance<upsertConnectorInstanceResponse>(getUpsertConnectorInstanceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      connectorInstantiationDto,)
  }
);}




export const getUpsertConnectorInstanceMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertConnectorInstance>>, TError,{data: BodyType<ConnectorInstantiationDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertConnectorInstance>>, TError,{data: BodyType<ConnectorInstantiationDto>}, TContext> => {

const mutationKey = ['upsertConnectorInstance'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertConnectorInstance>>, {data: BodyType<ConnectorInstantiationDto>}> = (props) => {
          const {data} = props ?? {};

          return  upsertConnectorInstance(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertConnectorInstanceMutationResult = NonNullable<Awaited<ReturnType<typeof upsertConnectorInstance>>>
    export type UpsertConnectorInstanceMutationBody = BodyType<ConnectorInstantiationDto>
    export type UpsertConnectorInstanceMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>

    /**
 * @summary Create or replace the instance of a distribution
 */
export const useUpsertConnectorInstance = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertConnectorInstance>>, TError,{data: BodyType<ConnectorInstantiationDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertConnectorInstance>>,
        TError,
        {data: BodyType<ConnectorInstantiationDto>},
        TContext
      > => {
      return useMutation(getUpsertConnectorInstanceMutationOptions(options), queryClient);
    }
    /**
 * @summary Get the instance of a distribution
 */
export type getConnectorInstanceByDistributionResponse200 = {
  data: ConnectorInstanceDto
  status: 200
}

export type getConnectorInstanceByDistributionResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getConnectorInstanceByDistributionResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getConnectorInstanceByDistributionResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type getConnectorInstanceByDistributionResponseSuccess = (getConnectorInstanceByDistributionResponse200) & {
  headers: Headers;
};
export type getConnectorInstanceByDistributionResponseError = (getConnectorInstanceByDistributionResponse400 | getConnectorInstanceByDistributionResponse401 | getConnectorInstanceByDistributionResponse404) & {
  headers: Headers;
};

export type getConnectorInstanceByDistributionResponse = (getConnectorInstanceByDistributionResponseSuccess | getConnectorInstanceByDistributionResponseError)

export const getGetConnectorInstanceByDistributionUrl = (distributionId: string,) => {


  

  return `/connector/instances/distribution/${distributionId}`
}

export const getConnectorInstanceByDistribution = async (distributionId: string, options?: RequestInit): Promise<getConnectorInstanceByDistributionResponse> => {
  
  return customInstance<getConnectorInstanceByDistributionResponse>(getGetConnectorInstanceByDistributionUrl(distributionId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetConnectorInstanceByDistributionInfiniteQueryKey = (distributionId: string,) => {
    return [
    'infinite', `/connector/instances/distribution/${distributionId}`
    ] as const;
    }

export const getGetConnectorInstanceByDistributionQueryKey = (distributionId: string,) => {
    return [
    `/connector/instances/distribution/${distributionId}`
    ] as const;
    }

    
export const getGetConnectorInstanceByDistributionInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(distributionId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConnectorInstanceByDistributionInfiniteQueryKey(distributionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>> = ({ signal }) => getConnectorInstanceByDistribution(distributionId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(distributionId),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetConnectorInstanceByDistributionInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>>
export type GetConnectorInstanceByDistributionInfiniteQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>


export function useGetConnectorInstanceByDistributionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 distributionId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>,
          TError,
          Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetConnectorInstanceByDistributionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 distributionId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>,
          TError,
          Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetConnectorInstanceByDistributionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 distributionId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get the instance of a distribution
 */

export function useGetConnectorInstanceByDistributionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 distributionId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetConnectorInstanceByDistributionInfiniteQueryOptions(distributionId,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetConnectorInstanceByDistributionQueryOptions = <TData = Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(distributionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConnectorInstanceByDistributionQueryKey(distributionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>> = ({ signal }) => getConnectorInstanceByDistribution(distributionId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(distributionId),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetConnectorInstanceByDistributionQueryResult = NonNullable<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>>
export type GetConnectorInstanceByDistributionQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>


export function useGetConnectorInstanceByDistribution<TData = Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 distributionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>,
          TError,
          Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetConnectorInstanceByDistribution<TData = Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 distributionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>,
          TError,
          Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetConnectorInstanceByDistribution<TData = Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 distributionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get the instance of a distribution
 */

export function useGetConnectorInstanceByDistribution<TData = Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 distributionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceByDistribution>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetConnectorInstanceByDistributionQueryOptions(distributionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get a connector instance
 */
export type getConnectorInstanceByIdResponse200 = {
  data: ConnectorInstanceDto
  status: 200
}

export type getConnectorInstanceByIdResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type getConnectorInstanceByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getConnectorInstanceByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type getConnectorInstanceByIdResponseSuccess = (getConnectorInstanceByIdResponse200) & {
  headers: Headers;
};
export type getConnectorInstanceByIdResponseError = (getConnectorInstanceByIdResponse400 | getConnectorInstanceByIdResponse401 | getConnectorInstanceByIdResponse404) & {
  headers: Headers;
};

export type getConnectorInstanceByIdResponse = (getConnectorInstanceByIdResponseSuccess | getConnectorInstanceByIdResponseError)

export const getGetConnectorInstanceByIdUrl = (id: string,) => {


  

  return `/connector/instances/${id}`
}

export const getConnectorInstanceById = async (id: string, options?: RequestInit): Promise<getConnectorInstanceByIdResponse> => {
  
  return customInstance<getConnectorInstanceByIdResponse>(getGetConnectorInstanceByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetConnectorInstanceByIdInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/connector/instances/${id}`
    ] as const;
    }

export const getGetConnectorInstanceByIdQueryKey = (id: string,) => {
    return [
    `/connector/instances/${id}`
    ] as const;
    }

    
export const getGetConnectorInstanceByIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getConnectorInstanceById>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConnectorInstanceByIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConnectorInstanceById>>> = ({ signal }) => getConnectorInstanceById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetConnectorInstanceByIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getConnectorInstanceById>>>
export type GetConnectorInstanceByIdInfiniteQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>


export function useGetConnectorInstanceByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getConnectorInstanceById>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectorInstanceById>>,
          TError,
          Awaited<ReturnType<typeof getConnectorInstanceById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetConnectorInstanceByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getConnectorInstanceById>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectorInstanceById>>,
          TError,
          Awaited<ReturnType<typeof getConnectorInstanceById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetConnectorInstanceByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getConnectorInstanceById>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get a connector instance
 */

export function useGetConnectorInstanceByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getConnectorInstanceById>>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetConnectorInstanceByIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetConnectorInstanceByIdQueryOptions = <TData = Awaited<ReturnType<typeof getConnectorInstanceById>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConnectorInstanceByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConnectorInstanceById>>> = ({ signal }) => getConnectorInstanceById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetConnectorInstanceByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getConnectorInstanceById>>>
export type GetConnectorInstanceByIdQueryError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>


export function useGetConnectorInstanceById<TData = Awaited<ReturnType<typeof getConnectorInstanceById>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectorInstanceById>>,
          TError,
          Awaited<ReturnType<typeof getConnectorInstanceById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetConnectorInstanceById<TData = Awaited<ReturnType<typeof getConnectorInstanceById>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectorInstanceById>>,
          TError,
          Awaited<ReturnType<typeof getConnectorInstanceById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetConnectorInstanceById<TData = Awaited<ReturnType<typeof getConnectorInstanceById>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get a connector instance
 */

export function useGetConnectorInstanceById<TData = Awaited<ReturnType<typeof getConnectorInstanceById>>, TError = ErrorType<BadRequestResponse | UnauthorizedResponse | NotFoundResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectorInstanceById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetConnectorInstanceByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Delete a connector instance
 */
export type deleteConnectorInstanceByIdResponse202 = {
  data: void
  status: 202
}

export type deleteConnectorInstanceByIdResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type deleteConnectorInstanceByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteConnectorInstanceByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteConnectorInstanceByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}
    
export type deleteConnectorInstanceByIdResponseSuccess = (deleteConnectorInstanceByIdResponse202) & {
  headers: Headers;
};
export type deleteConnectorInstanceByIdResponseError = (deleteConnectorInstanceByIdResponse400 | deleteConnectorInstanceByIdResponse401 | deleteConnectorInstanceByIdResponse403 | deleteConnectorInstanceByIdResponse404) & {
  headers: Headers;
};

export type deleteConnectorInstanceByIdResponse = (deleteConnectorInstanceByIdResponseSuccess | deleteConnectorInstanceByIdResponseError)

export const getDeleteConnectorInstanceByIdUrl = (id: string,) => {


  

  return `/connector/instances/${id}`
}

export const deleteConnectorInstanceById = async (id: string, options?: RequestInit): Promise<deleteConnectorInstanceByIdResponse> => {
  
  return customInstance<deleteConnectorInstanceByIdResponse>(getDeleteConnectorInstanceByIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteConnectorInstanceByIdMutationOptions = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteConnectorInstanceById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteConnectorInstanceById>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteConnectorInstanceById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteConnectorInstanceById>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteConnectorInstanceById(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteConnectorInstanceByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteConnectorInstanceById>>>
    
    export type DeleteConnectorInstanceByIdMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>

    /**
 * @summary Delete a connector instance
 */
export const useDeleteConnectorInstanceById = <TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteConnectorInstanceById>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteConnectorInstanceById>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteConnectorInstanceByIdMutationOptions(options), queryClient);
    }
    